
=====
===== LOGGING STARTED Fri Jan 12 16:36:37 CET 2024
=====

=====
===== LOGGING STARTED Fri Jan 12 16:36:37 CET 2024
=====
Erlang/OTP 27 [DEVELOPMENT] [erts-14.2.1] [source] [64-bit] [smp:1:1] [ds:1:1:1] [async-threads:1] [jit:ns]

Erlang/OTP 27 [DEVELOPMENT] [erts-14.2.1] [source] [64-bit] [smp:1:1] [ds:1:1:1] [async-threads:1] [jit:ns]

Logger - error: {removed_failing_handler,default}
Failed to write log message to stdout, trying stderr
=CRASH REPORT==== 12-Jan-2024::16:36:38.567254 ===
  crasher:
    initial call: peer:init_supervision/2
    pid: <0.71.0>
    registered_name: peer_supervision
    exception exit: {peer_channel_terminated,killed}
      in function  peer:loop_supervision/1 (peer.erl, line 1013)
      in call from peer:init_supervision/2 (peer.erl, line 991)
    ancestors: [kernel_sup,<0.47.0>]
    message_queue_len: 0
    messages: []
    links: [<0.49.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 376
    stack_size: 29
    reductions: 81
  neighbours:

Kernel pid terminated (application_controller) ("{application_terminated,kernel,shutdown}")

Crash dump is being written to: /buildroot/otp/lib/stdlib/make_test_dir/stdlib_erl_crash.dump...done

=====
===== LOGGING STARTED Fri Jan 12 16:36:54 CET 2024
=====

=====
===== LOGGING STARTED Fri Jan 12 16:36:54 CET 2024
=====
Erlang/OTP 27 [DEVELOPMENT] [erts-14.2.1] [source] [64-bit] [smp:1:1] [ds:1:1:1] [async-threads:1] [jit:ns]

Erlang/OTP 27 [DEVELOPMENT] [erts-14.2.1] [source] [64-bit] [smp:1:1] [ds:1:1:1] [async-threads:1] [jit:ns]

Eshell V14.2.1 (press Ctrl+G to abort, type help(). for help)
=CRASH REPORT==== 12-Jan-2024::16:36:56.379217 ===
  crasher:
    initial call: peer:init_supervision/2
    pid: <0.71.0>
    registered_name: peer_supervision
    exception exit: {peer_channel_terminated,killed}
      in function  peer:loop_supervision/1 (peer.erl, line 1013)
      in call from peer:init_supervision/2 (peer.erl, line 991)
    ancestors: [kernel_sup,<0.47.0>]
    message_queue_len: 0
    messages: []
    links: [<0.49.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 376
    stack_size: 29
    reductions: 81
  neighbours:

(peer_SUITE-attached_test-453027-17961@1ae2e8e74597)1> =SUPERVISOR REPORT==== 12-Jan-2024::16:36:56.397903 ===
    supervisor: {local,kernel_sup}
    errorContext: child_terminated
    reason: {peer_channel_terminated,killed}
    offender: [{pid,<0.71.0>},
               {id,peer_supervision},
               {mfargs,{peer,start_supervision,[]}},
               {restart_type,permanent},
               {significant,false},
               {shutdown,1000},
               {child_type,worker}]

=SUPERVISOR REPORT==== 12-Jan-2024::16:36:56.398001 ===
    supervisor: {local,kernel_sup}
    errorContext: shutdown
    reason: reached_max_restart_intensity
    offender: [{pid,<0.71.0>},
               {id,peer_supervision},
               {mfargs,{peer,start_supervision,[]}},
               {restart_type,permanent},
               {significant,false},
               {shutdown,1000},
               {child_type,worker}]

Kernel pid terminated (application_controller) ("{application_terminated,kernel,shutdown}")

Crash dump is being written to: /buildroot/otp/lib/stdlib/make_test_dir/stdlib_erl_crash.dump...done
