
=====
===== LOGGING STARTED Tue Jul  9 22:03:07 CEST 2024
=====

=====
===== LOGGING STARTED Tue Jul  9 22:03:07 CEST 2024
=====
Erlang/OTP 28 [DEVELOPMENT] [erts-15.0] [source] [64-bit] [smp:1:1] [ds:1:1:1] [async-threads:1] [jit:ns]

Erlang/OTP 28 [DEVELOPMENT] [erts-15.0] [source] [64-bit] [smp:1:1] [ds:1:1:1] [async-threads:1] [jit:ns]

Logger - error: {removed_failing_handler,default}
Failed to write log message to stdout, trying stderr
=CRASH REPORT==== 9-Jul-2024::22:03:08.700176 ===
  crasher:
    initial call: peer:init_supervision/2
    pid: <0.71.0>
    registered_name: peer_supervision
    exception exit: {peer_channel_terminated,killed}
      in function  peer:loop_supervision/1 (peer.erl, line 1303)
      in call from peer:init_supervision/2 (peer.erl, line 1281)
    ancestors: [kernel_sup,<0.47.0>]
    message_queue_len: 0
    messages: []
    links: [<0.49.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 376
    stack_size: 29
    reductions: 81
  neighbours:

Kernel pid terminated (application_controller) ("{application_terminated,kernel,shutdown}")

Crash dump is being written to: /buildroot/otp/lib/stdlib/make_test_dir/stdlib_erl_crash.dump...done

=====
===== LOGGING STARTED Tue Jul  9 22:03:23 CEST 2024
=====

=====
===== LOGGING STARTED Tue Jul  9 22:03:23 CEST 2024
=====
Erlang/OTP 28 [DEVELOPMENT] [erts-15.0] [source] [64-bit] [smp:1:1] [ds:1:1:1] [async-threads:1] [jit:ns]

Erlang/OTP 28 [DEVELOPMENT] [erts-15.0] [source] [64-bit] [smp:1:1] [ds:1:1:1] [async-threads:1] [jit:ns]

Eshell V15.0 (press Ctrl+G to abort, type help(). for help)
(peer_SUITE-attached_test-420355-11793@d871d56956c2)1> =CRASH REPORT==== 9-Jul-2024::22:03:24.939228 ===
  crasher:
    initial call: peer:init_supervision/2
    pid: <0.71.0>
    registered_name: peer_supervision
    exception exit: {peer_channel_terminated,killed}
      in function  peer:loop_supervision/1 (peer.erl, line 1303)
      in call from peer:init_supervision/2 (peer.erl, line 1281)
    ancestors: [kernel_sup,<0.47.0>]
    message_queue_len: 0
    messages: []
    links: [<0.49.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 376
    stack_size: 29
    reductions: 81
  neighbours:

=SUPERVISOR REPORT==== 9-Jul-2024::22:03:24.950380 ===
    supervisor: {local,kernel_sup}
    errorContext: child_terminated
    reason: {peer_channel_terminated,killed}
    offender: [{pid,<0.71.0>},
               {id,peer_supervision},
               {mfargs,{peer,start_supervision,[]}},
               {restart_type,permanent},
               {significant,false},
               {shutdown,1000},
               {child_type,worker}]

=SUPERVISOR REPORT==== 9-Jul-2024::22:03:24.950508 ===
    supervisor: {local,kernel_sup}
    errorContext: shutdown
    reason: reached_max_restart_intensity
    offender: [{pid,<0.71.0>},
               {id,peer_supervision},
               {mfargs,{peer,start_supervision,[]}},
               {restart_type,permanent},
               {significant,false},
               {shutdown,1000},
               {child_type,worker}]

Kernel pid terminated (application_controller) ("{application_terminated,kernel,shutdown}")

Crash dump is being written to: /buildroot/otp/lib/stdlib/make_test_dir/stdlib_erl_crash.dump...done
