<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>Unexpected I/O log</title>
<meta http-equiv="cache-control" content="no-cache"></meta>
<meta http-equiv="content-type" content="text/html; charset=utf-8"></meta>
<link rel="stylesheet" href="../../ct_default.css" type="text/css"></link>
<script type="text/javascript" src="../../jquery-latest.js"></script>
<script type="text/javascript" src="../../jquery.tablesorter.min.js"></script>
</head>
<body>

<br />
<h3>Unexpected I/O</h3>
<pre>

</pre>
<div class="error_logger"><pre><b>*** System report during multi_call_parallel in gen_server_SUITE 2025-01-24 10:49:16.238 ***</b>
=ERROR REPORT==== 24-Jan-2025::10:49:16.238267 ===
** Generic server my_test_name terminating 
** Last message in was stop
** When Server state == {formatted,[]}
** Reason for termination ==
** stopped
** Client <0.247066.0> stacktrace
** [{gen_server,mc_recv,5,[{file,"gen_server.erl"},{line,1983}]},
    {gen_server,multi_call,4,[{file,"gen_server.erl"},{line,1944}]},
    {gen_server_SUITE,multicall,1,[{file,"gen_server_SUITE.erl"},{line,1487}]},
    {test_server,ts_tc,3,[{file,"test_server.erl"},{line,1794}]},
    {test_server,run_test_case_eval1,6,[{file,"test_server.erl"},{line,1303}]},
    {test_server,run_test_case_eval,9,[{file,"test_server.erl"},{line,1235}]}]


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during multi_call_parallel in gen_server_SUITE 2025-01-24 10:49:16.238 ***</b>
=CRASH REPORT==== 24-Jan-2025::10:49:16.238767 ===
  crasher:
    initial call: gen_server_SUITE:init/1
    pid: <0.247071.0>
    registered_name: my_test_name
    exception exit: stopped
      in function  gen_server:handle_msg/3 (gen_server.erl, line 2435)
    ancestors: [<0.247066.0>]
    message_queue_len: 0
    messages: []
    links: [<0.247066.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 987
    stack_size: 29
    reductions: 590
  neighbours:


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during gen_server_SUITE:spec_init/1 2025-01-24 10:49:56.340 ***</b>
=ERROR REPORT==== 24-Jan-2025::10:49:56.340752 ===
** Generic server hurra terminating 
** Last message in was {'EXIT',&lt;0.251416.0&gt;,
                               {#Ref&lt;0.3740098887.2158755841.256048&gt;,1003282,
                                ok,
                                [{gen_server_SUITE,spec_init}],
                                []}}
** When Server state == {formatted,{}}
** Reason for termination ==
** {#Ref&lt;0.3740098887.2158755841.256048&gt;,1003282,ok,
    [{gen_server_SUITE,spec_init}],
    []}


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during gen_server_SUITE:spec_init/1 2025-01-24 10:49:56.341 ***</b>
=CRASH REPORT==== 24-Jan-2025::10:49:56.341000 ===
  crasher:
    initial call: gen_server_SUITE:spec_init_global_default_timeout/2
    pid: &lt;0.251436.0&gt;
    registered_name: []
    exception exit: {#Ref&lt;0.3740098887.2158755841.256048&gt;,1003282,ok,
                     [{gen_server_SUITE,spec_init}],
                     []}
      in function  gen_server:decode_msg/6 (gen_server.erl, line 2309)
    ancestors: [&lt;0.251416.0&gt;]
    message_queue_len: 0
    messages: []
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 29
    reductions: 413
  neighbours:


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during log_mf_h_SUITE:test/1 2025-01-24 10:54:38.663 ***</b>
=CRASH REPORT==== 24-Jan-2025::10:54:38.663346 ===
  crasher:
    initial call: gen_event:init_it/6
    pid: &lt;0.257251.0&gt;
    registered_name: []
    exception exit: {#Ref&lt;0.3740098887.2160328705.94603&gt;,5839,
                     {ok,3},
                     [{log_mf_h_SUITE,test}],
                     []}
      in function  gen_event:terminate_server/4 (gen_event.erl, line 1696)
    ancestors: [&lt;0.257249.0&gt;]
    message_queue_len: 0
    messages: []
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 4185
    stack_size: 29
    reductions: 28661
  neighbours:


</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during dist in peer_SUITE 2025-01-24 10:54:48.376 ***</b>
=ERROR REPORT==== 24-Jan-2025::10:54:48.375797 ===
** Generic server <0.258546.0> terminating 
** Last message in was {nodedown,'peer_down_crash-500098-11901@a6b1b5c4700f'}
** When Server state == {peer_state,
                            #{args => ["-connect_all","false"],
                              name => "peer_down_crash-500098-11901",
                              peer_down => crash},
                            'peer_down_crash-500098-11901@a6b1b5c4700f',
                            [47,98,117,105,108,100,114,111,111,116,47,111,116,
                             112,47,69,114,108,97,110,103,32,8709,8868,8478,
                             47,101,114,116,115,45,49,53,46,50,46,49,47,98,
                             105,110,47,101,114,108],
                            ["-sname","peer_down_crash-500098-11901",
                             "-connect_all","false","-detached",
                             "-peer_detached","-user","peer","-origin",
                             "g1h3GHRlc3Rfc2VydmVyQGE2YjFiNWM0NzAwZgAD8fIAAAAAZ5NfeA=="],
                            undefined,undefined,<<>>,
                            {down,
                                {nodedown,
                                    'peer_down_crash-500098-11901@a6b1b5c4700f'}},
                            {<0.258524.0>,
                             #Ref<0.3740098887.2160328705.109076>},
                            0,#{}}
** Reason for termination ==
** {nodedown,'peer_down_crash-500098-11901@a6b1b5c4700f'}


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during dist in peer_SUITE 2025-01-24 10:54:48.376 ***</b>
=CRASH REPORT==== 24-Jan-2025::10:54:48.376145 ===
  crasher:
    initial call: peer:init/1
    pid: <0.258546.0>
    registered_name: []
    exception exit: {nodedown,'peer_down_crash-500098-11901@a6b1b5c4700f'}
      in function  gen_server:handle_common_reply/5 (gen_server.erl, line 2483)
    ancestors: [<0.258524.0>]
    message_queue_len: 0
    messages: []
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 1598
    stack_size: 29
    reductions: 1498
  neighbours:


</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during dist in peer_SUITE 2025-01-24 10:54:49.220 ***</b>
=WARNING REPORT==== 24-Jan-2025::10:54:48.218562 ===
Process <0.92.0> on node 'peer_SUITE-shutdown_stop-379749-11901@a6b1b5c4700f' enabled access to the emulator internal state.
NOTE: This is an erts internal test feature and should *only* be used by OTP test-suites.



</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during dist in peer_SUITE 2025-01-24 10:54:49.865 ***</b>
=WARNING REPORT==== 24-Jan-2025::10:54:49.865257 ===
peer:stop() timed out waiting for disconnect from node 'peer_SUITE-shutdown_stop_timeout-379717-11901@a6b1b5c4700f'. The connection was forcefully taken down.

</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during dist in peer_SUITE 2025-01-24 10:54:49.894 ***</b>
=WARNING REPORT==== 24-Jan-2025::10:54:49.894124 ===
peer:stop() timed out waiting for disconnect from node 'peer_SUITE-shutdown_halt_timeout-379685-11901@a6b1b5c4700f'. The connection was forcefully taken down.

</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during tcp in peer_SUITE 2025-01-24 10:55:05.634 ***</b>
=WARNING REPORT==== 24-Jan-2025::10:55:04.632621 ===
Process <0.89.0> on node 'peer_SUITE-shutdown_stop-452163-11901@a6b1b5c4700f' enabled access to the emulator internal state.
NOTE: This is an erts internal test feature and should *only* be used by OTP test-suites.



</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during tcp in peer_SUITE 2025-01-24 10:55:06.025 ***</b>
=WARNING REPORT==== 24-Jan-2025::10:55:06.025249 ===
peer:stop() timed out waiting for disconnect from node 'peer_SUITE-shutdown_stop_timeout-422852-11901@a6b1b5c4700f'. The connection was forcefully taken down.

</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during tcp in peer_SUITE 2025-01-24 10:55:06.124 ***</b>
=WARNING REPORT==== 24-Jan-2025::10:55:06.124125 ===
peer:stop() timed out waiting for disconnect from node 'peer_SUITE-shutdown_halt_timeout-500898-11901@a6b1b5c4700f'. The connection was forcefully taken down.

</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during standard_io in peer_SUITE 2025-01-24 10:55:08.371 ***</b>
=ERROR REPORT==== 24-Jan-2025::10:55:08.370840 ===
** Generic server <0.258886.0> terminating 
** Last message in was {'EXIT',<0.258883.0>,
                               {#Ref<0.3740098887.2153250818.18239>,1645442,
                                ok,
                                [{peer_SUITE,cntrl_channel_handler_crash}],
                                []}}
** When Server state == {peer_state,#{name =>
                                          "peer_SUITE-cntrl_channel_handler_crash-452707-11901",
                                      connection => standard_io},
                                    'peer_SUITE-cntrl_channel_handler_crash-452707-11901@a6b1b5c4700f',
                                    [47,98,117,105,108,100,114,111,111,116,47,
                                     111,116,112,47,69,114,108,97,110,103,32,
                                     8709,8868,8478,47,101,114,116,115,45,49,
                                     53,46,50,46,49,47,98,105,110,47,101,114,
                                     108],
                                    ["-sname",
                                     "peer_SUITE-cntrl_channel_handler_crash-452707-11901",
                                     "-user","peer"],
                                    #Port<0.3130>,undefined,<<>>,running,
                                    {<0.258883.0>,
                                     #Ref<0.3740098887.2153250818.18249>},
                                    0,#{}}
** Reason for termination ==
** {#Ref<0.3740098887.2153250818.18239>,1645442,ok,
    [{peer_SUITE,cntrl_channel_handler_crash}],
    []}


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during standard_io in peer_SUITE 2025-01-24 10:55:08.371 ***</b>
=CRASH REPORT==== 24-Jan-2025::10:55:08.371146 ===
  crasher:
    initial call: peer:init/1
    pid: <0.258886.0>
    registered_name: []
    exception exit: {#Ref<0.3740098887.2153250818.18239>,1645442,ok,
                     [{peer_SUITE,cntrl_channel_handler_crash}],
                     []}
      in function  gen_server:decode_msg/6 (gen_server.erl, line 2309)
    ancestors: [<0.258883.0>]
    message_queue_len: 1
    messages: [{'EXIT',#Port<0.3130>,normal}]
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 2586
    stack_size: 29
    reductions: 4705
  neighbours:


</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during standard_io in peer_SUITE 2025-01-24 10:55:08.939 ***</b>
=ERROR REPORT==== 24-Jan-2025::10:55:08.939535 ===
** Generic server <0.258922.0> terminating 
** Last message in was {'EXIT',<0.258889.0>,
                           {#Ref<0.3740098887.2160328705.113230>,2206994,ok,
                            [{peer_SUITE,
                                 cntrl_channel_handler_crash_old_release}],
                            []}}
** When Server state == {peer_state,#{args =>
                                          ["-setcookie",
                                           "AVLQPIVVTLDTRFSAMLEW","-pa",
                                           "/buildroot/otp/lib/stdlib/make_test_dir/stdlib_test",
                                           "-env","ERL_CRASH_DUMP",
                                           "/buildroot/otp/lib/stdlib/make_test_dir/ct_logs/ct_run.test_server@a6b1b5c4700f.2025-01-24_10.37.59/erl_crash_dump.peer_SUITE-cntrl_channel_handler_crash_old_release-423204-11901",
                                           "-pa",
                                           "/buildroot/otp/lib/stdlib/make_test_dir/ct_logs/ct_run.test_server@a6b1b5c4700f.2025-01-24_10.37.59/make_test_dir.stdlib_test.logs/run.2025-01-24_10.38.35/log_private/"],
                                      env => [{"ERL_AFLAGS",false}],
                                      name =>
                                          "peer_SUITE-cntrl_channel_handler_crash_old_release-423204-11901",
                                      connection => standard_io,
                                      exec =>
                                          "/usr/local/lib/erlang-26.2.5.6/bin/erl",
                                      start_cover => false},
                                    'peer_SUITE-cntrl_channel_handler_crash_old_release-423204-11901@a6b1b5c4700f',
                                    "/usr/local/lib/erlang-26.2.5.6/bin/erl",
                                    ["-sname",
                                     "peer_SUITE-cntrl_channel_handler_crash_old_release-423204-11901",
                                     "-setcookie","AVLQPIVVTLDTRFSAMLEW",
                                     "-pa",
                                     "/buildroot/otp/lib/stdlib/make_test_dir/stdlib_test",
                                     "-env","ERL_CRASH_DUMP",
                                     "/buildroot/otp/lib/stdlib/make_test_dir/ct_logs/ct_run.test_server@a6b1b5c4700f.2025-01-24_10.37.59/erl_crash_dump.peer_SUITE-cntrl_channel_handler_crash_old_release-423204-11901",
                                     "-pa",
                                     "/buildroot/otp/lib/stdlib/make_test_dir/ct_logs/ct_run.test_server@a6b1b5c4700f.2025-01-24_10.37.59/make_test_dir.stdlib_test.logs/run.2025-01-24_10.38.35/log_private/",
                                     "-user","peer"],
                                    #Port<0.3156>,undefined,<<>>,running,
                                    {<0.258889.0>,
                                     #Ref<0.3740098887.2152726531.192640>},
                                    0,#{}}
** Reason for termination ==
** {#Ref<0.3740098887.2160328705.113230>,2206994,ok,
    [{peer_SUITE,cntrl_channel_handler_crash_old_release}],
    []}


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during standard_io in peer_SUITE 2025-01-24 10:55:08.940 ***</b>
=CRASH REPORT==== 24-Jan-2025::10:55:08.939975 ===
  crasher:
    initial call: peer:init/1
    pid: <0.258922.0>
    registered_name: []
    exception exit: {#Ref<0.3740098887.2160328705.113230>,2206994,ok,
                     [{peer_SUITE,cntrl_channel_handler_crash_old_release}],
                     []}
      in function  gen_server:decode_msg/6 (gen_server.erl, line 2309)
    ancestors: [<0.258889.0>]
    message_queue_len: 1
    messages: [{'EXIT',#Port<0.3156>,normal}]
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 2586
    stack_size: 29
    reductions: 4328
  neighbours:


</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during standard_io in peer_SUITE 2025-01-24 10:55:09.319 ***</b>
=WARNING REPORT==== 24-Jan-2025::10:55:08.318249 ===
Process <0.89.0> on node 'peer_SUITE-shutdown_stop-423236-11901@a6b1b5c4700f' enabled access to the emulator internal state.
NOTE: This is an erts internal test feature and should *only* be used by OTP test-suites.



</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during standard_io in peer_SUITE 2025-01-24 10:55:09.448 ***</b>
=WARNING REPORT==== 24-Jan-2025::10:55:09.448207 ===
peer:stop() timed out waiting for disconnect from node 'init_debug-380101-11901@a6b1b5c4700f'. The connection was forcefully taken down.

</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during standard_io in peer_SUITE 2025-01-24 10:55:09.713 ***</b>
=WARNING REPORT==== 24-Jan-2025::10:55:09.713212 ===
peer:stop() timed out waiting for disconnect from node 'peer_SUITE-shutdown_stop_timeout-380133-11901@a6b1b5c4700f'. The connection was forcefully taken down.

</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during standard_io in peer_SUITE 2025-01-24 10:55:09.772 ***</b>
=WARNING REPORT==== 24-Jan-2025::10:55:09.772158 ===
peer:stop() timed out waiting for disconnect from node 'peer_SUITE-shutdown_halt_timeout-501218-11901@a6b1b5c4700f'. The connection was forcefully taken down.

</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during supervisor_SUITE:temporary_bystander/1 2025-01-24 11:17:19.812 ***</b>
=ERROR REPORT==== 24-Jan-2025::11:17:19.811749 ===
** Generic server <0.335812.0> terminating 
** Last message in was {'EXIT',<0.335810.0>,
                               {#Ref<0.3740098887.2192310273.188348>,350931,
                                [{child1,<0.335819.0>,worker,[]}],
                                [{supervisor_SUITE,temporary_bystander}],
                                []}}
** When Server state == {state,
                            {<0.335812.0>,supervisor_SUITE},
                            one_for_all,
                            {[child1],
                             #{child1 =>
                                   {child,<0.335818.0>,child1,
                                       {supervisor_1,start_child,[]},
                                       permanent,false,100,worker,[]}}},
                            undefined,2,300,
                            [-576458392],
                            1,0,never,supervisor_SUITE,
                            {ok,{{one_for_all,2,300},[]}}}
** Reason for termination ==
** {#Ref<0.3740098887.2192310273.188348>,350931,
    [{child1,<0.335819.0>,worker,[]}],
    [{supervisor_SUITE,temporary_bystander}],
    []}


</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during supervisor_SUITE:temporary_bystander/1 2025-01-24 11:17:19.812 ***</b>
=ERROR REPORT==== 24-Jan-2025::11:17:19.811749 ===
** Generic server <0.335813.0> terminating 
** Last message in was {'EXIT',<0.335810.0>,
                               {#Ref<0.3740098887.2192310273.188348>,350931,
                                [{child1,<0.335819.0>,worker,[]}],
                                [{supervisor_SUITE,temporary_bystander}],
                                []}}
** When Server state == {state,
                            {<0.335813.0>,supervisor_SUITE},
                            rest_for_one,
                            {[child1],
                             #{child1 =>
                                   {child,<0.335819.0>,child1,
                                       {supervisor_1,start_child,[]},
                                       permanent,false,100,worker,[]}}},
                            undefined,2,300,
                            [-576458392],
                            1,0,never,supervisor_SUITE,
                            {ok,{{rest_for_one,2,300},[]}}}
** Reason for termination ==
** {#Ref<0.3740098887.2192310273.188348>,350931,
    [{child1,<0.335819.0>,worker,[]}],
    [{supervisor_SUITE,temporary_bystander}],
    []}


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during supervisor_SUITE:temporary_bystander/1 2025-01-24 11:17:19.812 ***</b>
=CRASH REPORT==== 24-Jan-2025::11:17:19.812253 ===
  crasher:
    initial call: supervisor:supervisor_SUITE/1
    pid: <0.335812.0>
    registered_name: []
    exception exit: {#Ref<0.3740098887.2192310273.188348>,350931,
                     [{child1,<0.335819.0>,worker,[]}],
                     [{supervisor_SUITE,temporary_bystander}],
                     []}
      in function  gen_server:decode_msg/6 (gen_server.erl, line 2309)
    ancestors: [<0.335810.0>]
    message_queue_len: 0
    messages: []
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 1598
    stack_size: 29
    reductions: 1005
  neighbours:


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during supervisor_SUITE:temporary_bystander/1 2025-01-24 11:17:19.812 ***</b>
=CRASH REPORT==== 24-Jan-2025::11:17:19.812456 ===
  crasher:
    initial call: supervisor:supervisor_SUITE/1
    pid: <0.335813.0>
    registered_name: []
    exception exit: {#Ref<0.3740098887.2192310273.188348>,350931,
                     [{child1,<0.335819.0>,worker,[]}],
                     [{supervisor_SUITE,temporary_bystander}],
                     []}
      in function  gen_server:decode_msg/6 (gen_server.erl, line 2309)
    ancestors: [<0.335810.0>]
    message_queue_len: 0
    messages: []
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 1598
    stack_size: 29
    reductions: 1026
  neighbours:


</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during zzz_SUITE:lc_graph/1 2025-01-24 11:43:37.561 ***</b>
=WARNING REPORT==== 24-Jan-2025::11:43:37.559664 ===
Process <0.439395.0> on node 'test_server@a6b1b5c4700f' enabled access to the emulator internal state.
NOTE: This is an erts internal test feature and should *only* be used by OTP test-suites.



</pre></div>
<pre>
</pre>
<center>
<br /><hr /><p>
<a href="../../../all_runs.html">Test run history
</a>  |  <a href="../../../index.html">Top level test index
</a>  |  <a href="../../../suite.log.latest.html">Latest test result</a>
</p>
<div class="copyright">Copyright &copy; 2025 <a href="http://www.erlang.org">Open Telecom Platform</a><br />
Updated: <!--date-->Fri Jan 24 2025 10:38:35<!--/date--><br />
</div>
</center>
</body>
</html>
