<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>Unexpected I/O log</title>
<meta http-equiv="cache-control" content="no-cache"></meta>
<meta http-equiv="content-type" content="text/html; charset=utf-8"></meta>
<link rel="stylesheet" href="../../ct_default.css" type="text/css"></link>
<script type="text/javascript" src="../../jquery-latest.js"></script>
<script type="text/javascript" src="../../jquery.tablesorter.min.js"></script>
</head>
<body>

<br />
<h3>Unexpected I/O</h3>
<pre>

</pre>
<div class="sasl"><pre><b>*** System report during gen_server_SUITE:abcast/1 2024-03-04 18:10:16.098 ***</b>
=CRASH REPORT==== 4-Mar-2024::18:10:16.098200 ===
  crasher:
    initial call: gen_server_SUITE:init/1
    pid: &lt;0.244284.0&gt;
    registered_name: my_test_name
    exception exit: {&lt;0.244282.0&gt;,stopped}
      in function  gen_server:handle_common_reply/8 (gen_server.erl, line 2306)
    ancestors: [&lt;0.244282.0&gt;]
    message_queue_len: 0
    messages: []
    links: []
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 2586
    stack_size: 29
    reductions: 3581
  neighbours:


</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during multi_call_parallel in gen_server_SUITE 2024-03-04 18:10:18.198 ***</b>
=ERROR REPORT==== 4-Mar-2024::18:10:18.198031 ===
** Generic server my_test_name terminating 
** Last message in was stop
** When Server state == {formatted,[]}
** Reason for termination ==
** stopped
** Client <0.244309.0> stacktrace
** [{gen_server,mc_recv,5,[{file,"gen_server.erl"},{line,1807}]},
    {gen_server,multi_call,4,[{file,"gen_server.erl"},{line,1768}]},
    {gen_server_SUITE,multicall,1,[{file,"gen_server_SUITE.erl"},{line,1487}]},
    {test_server,ts_tc,3,[{file,"test_server.erl"},{line,1794}]},
    {test_server,run_test_case_eval1,6,[{file,"test_server.erl"},{line,1303}]},
    {test_server,run_test_case_eval,9,[{file,"test_server.erl"},{line,1235}]}]


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during multi_call_parallel in gen_server_SUITE 2024-03-04 18:10:18.198 ***</b>
=CRASH REPORT==== 4-Mar-2024::18:10:18.198540 ===
  crasher:
    initial call: gen_server_SUITE:init/1
    pid: <0.244313.0>
    registered_name: my_test_name
    exception exit: stopped
      in function  gen_server:handle_msg/6 (gen_server.erl, line 2256)
    ancestors: [<0.244309.0>]
    message_queue_len: 0
    messages: []
    links: [<0.244309.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 2586
    stack_size: 29
    reductions: 6877
  neighbours:


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during gen_server_SUITE:spec_init/1 2024-03-04 18:10:56.669 ***</b>
=ERROR REPORT==== 4-Mar-2024::18:10:56.669528 ===
** Generic server hurra terminating 
** Last message in was {'EXIT',&lt;0.248660.0&gt;,
                               {#Ref&lt;0.2190842303.2220359681.7541&gt;,1006706,ok,
                                [{gen_server_SUITE,spec_init}],
                                []}}
** When Server state == {formatted,{}}
** Reason for termination ==
** {#Ref&lt;0.2190842303.2220359681.7541&gt;,1006706,ok,
    [{gen_server_SUITE,spec_init}],
    []}


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during gen_server_SUITE:spec_init/1 2024-03-04 18:10:56.670 ***</b>
=CRASH REPORT==== 4-Mar-2024::18:10:56.669939 ===
  crasher:
    initial call: gen_server_SUITE:spec_init_global_default_timeout/2
    pid: &lt;0.248679.0&gt;
    registered_name: []
    exception exit: {#Ref&lt;0.2190842303.2220359681.7541&gt;,1006706,ok,
                     [{gen_server_SUITE,spec_init}],
                     []}
      in function  gen_server:decode_msg/9 (gen_server.erl, line 2129)
    ancestors: [&lt;0.248660.0&gt;]
    message_queue_len: 0
    messages: []
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 4185
    stack_size: 29
    reductions: 4571
  neighbours:


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during gen_server_SUITE:spec_init_local_registered_parent/1 2024-03-04 18:10:56.692 ***</b>
=CRASH REPORT==== 4-Mar-2024::18:10:56.692783 ===
  crasher:
    initial call: gen_server_SUITE:spec_init_local/2
    pid: &lt;0.248686.0&gt;
    registered_name: my_server
    exception exit: {&lt;0.248684.0&gt;,stopped}
      in function  gen_server:handle_common_reply/8 (gen_server.erl, line 2306)
    ancestors: [foobar]
    message_queue_len: 0
    messages: []
    links: [&lt;0.248684.0&gt;]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 2586
    stack_size: 29
    reductions: 3429
  neighbours:


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during log_mf_h_SUITE:test/1 2024-03-04 18:15:31.695 ***</b>
=CRASH REPORT==== 4-Mar-2024::18:15:31.695612 ===
  crasher:
    initial call: gen_event:init_it/6
    pid: &lt;0.254085.0&gt;
    registered_name: []
    exception exit: {#Ref&lt;0.2190842303.2221670401.149777&gt;,5842,
                     {ok,3},
                     [{log_mf_h_SUITE,test}],
                     []}
      in function  gen_event:terminate_server/4 (gen_event.erl, line 1529)
    ancestors: [&lt;0.254083.0&gt;]
    message_queue_len: 0
    messages: []
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 4185
    stack_size: 29
    reductions: 28723
  neighbours:


</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during dist in peer_SUITE 2024-03-04 18:15:41.076 ***</b>
=ERROR REPORT==== 4-Mar-2024::18:15:41.076571 ===
** Generic server <0.255368.0> terminating 
** Last message in was {nodedown,'peer_down_crash-394565-11805@f307f798be6e'}
** When Server state == {peer_state,
                            #{args => ["-connect_all","false"],
                              name => "peer_down_crash-394565-11805",
                              peer_down => crash},
                            'peer_down_crash-394565-11805@f307f798be6e',
                            [47,98,117,105,108,100,114,111,111,116,47,111,116,
                             112,47,69,114,108,97,110,103,32,8709,8868,8478,
                             47,101,114,116,115,45,49,52,46,50,46,50,47,98,
                             105,110,47,101,114,108],
                            ["-sname","peer_down_crash-394565-11805",
                             "-connect_all","false","-detached",
                             "-peer_detached","-user","peer","-origin",
                             "g1h3GHRlc3Rfc2VydmVyQGYzMDdmNzk4YmU2ZQAD5YgAAAAAZeX+KA=="],
                            undefined,undefined,<<>>,
                            {down,
                                {nodedown,
                                    'peer_down_crash-394565-11805@f307f798be6e'}},
                            {<0.255355.0>,#Ref<0.2190842303.2213806084.4780>},
                            0,#{}}
** Reason for termination ==
** {nodedown,'peer_down_crash-394565-11805@f307f798be6e'}


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during dist in peer_SUITE 2024-03-04 18:15:41.078 ***</b>
=CRASH REPORT==== 4-Mar-2024::18:15:41.077200 ===
  crasher:
    initial call: peer:init/1
    pid: <0.255368.0>
    registered_name: []
    exception exit: {nodedown,'peer_down_crash-394565-11805@f307f798be6e'}
      in function  gen_server:handle_common_reply/8 (gen_server.erl, line 2306)
    ancestors: [<0.255355.0>]
    message_queue_len: 0
    messages: []
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 6772
    stack_size: 29
    reductions: 11213
  neighbours:


</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during dist in peer_SUITE 2024-03-04 18:15:42.121 ***</b>
=WARNING REPORT==== 4-Mar-2024::18:15:41.120895 ===
Process <0.90.0> on node 'peer_SUITE-shutdown_stop-394629-11805@f307f798be6e' enabled access to the emulator internal state.
NOTE: This is an erts internal test feature and should *only* be used by OTP test-suites.



</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during dist in peer_SUITE 2024-03-04 18:15:42.604 ***</b>
=WARNING REPORT==== 4-Mar-2024::18:15:42.604042 ===
peer:stop() timed out waiting for disconnect from node 'peer_SUITE-shutdown_halt_timeout-394725-11805@f307f798be6e'. The connection was forcefully taken down.

</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during dist in peer_SUITE 2024-03-04 18:15:42.652 ***</b>
=WARNING REPORT==== 4-Mar-2024::18:15:42.652022 ===
peer:stop() timed out waiting for disconnect from node 'peer_SUITE-shutdown_stop_timeout-394661-11805@f307f798be6e'. The connection was forcefully taken down.

</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during tcp in peer_SUITE 2024-03-04 18:15:58.877 ***</b>
=WARNING REPORT==== 4-Mar-2024::18:15:57.875433 ===
Process <0.87.0> on node 'peer_SUITE-shutdown_stop-394885-11805@f307f798be6e' enabled access to the emulator internal state.
NOTE: This is an erts internal test feature and should *only* be used by OTP test-suites.



</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during tcp in peer_SUITE 2024-03-04 18:15:59.412 ***</b>
=WARNING REPORT==== 4-Mar-2024::18:15:59.412119 ===
peer:stop() timed out waiting for disconnect from node 'peer_SUITE-shutdown_stop_timeout-454851-11805@f307f798be6e'. The connection was forcefully taken down.

</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during tcp in peer_SUITE 2024-03-04 18:15:59.457 ***</b>
=WARNING REPORT==== 4-Mar-2024::18:15:59.457004 ===
peer:stop() timed out waiting for disconnect from node 'peer_SUITE-shutdown_halt_timeout-454819-11805@f307f798be6e'. The connection was forcefully taken down.

</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during standard_io in peer_SUITE 2024-03-04 18:16:02.162 ***</b>
=ERROR REPORT==== 4-Mar-2024::18:16:02.162649 ===
** Generic server <0.255715.0> terminating 
** Last message in was {'EXIT',<0.255696.0>,
                               {#Ref<0.2190842303.2214330370.186013>,1550642,
                                ok,
                                [{peer_SUITE,cntrl_channel_handler_crash}],
                                []}}
** When Server state == {peer_state,#{name =>
                                          "peer_SUITE-cntrl_channel_handler_crash-496290-11805",
                                      connection => standard_io},
                                    'peer_SUITE-cntrl_channel_handler_crash-496290-11805@f307f798be6e',
                                    [47,98,117,105,108,100,114,111,111,116,47,
                                     111,116,112,47,69,114,108,97,110,103,32,
                                     8709,8868,8478,47,101,114,116,115,45,49,
                                     52,46,50,46,50,47,98,105,110,47,101,114,
                                     108],
                                    ["-sname",
                                     "peer_SUITE-cntrl_channel_handler_crash-496290-11805",
                                     "-user","peer"],
                                    #Port<0.3095>,undefined,<<>>,running,
                                    {<0.255696.0>,
                                     #Ref<0.2190842303.2221670401.170834>},
                                    0,#{}}
** Reason for termination ==
** {#Ref<0.2190842303.2214330370.186013>,1550642,ok,
    [{peer_SUITE,cntrl_channel_handler_crash}],
    []}


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during standard_io in peer_SUITE 2024-03-04 18:16:02.163 ***</b>
=CRASH REPORT==== 4-Mar-2024::18:16:02.163234 ===
  crasher:
    initial call: peer:init/1
    pid: <0.255715.0>
    registered_name: []
    exception exit: {#Ref<0.2190842303.2214330370.186013>,1550642,ok,
                     [{peer_SUITE,cntrl_channel_handler_crash}],
                     []}
      in function  gen_server:decode_msg/9 (gen_server.erl, line 2129)
    ancestors: [<0.255696.0>]
    message_queue_len: 1
    messages: [{'EXIT',#Port<0.3095>,normal}]
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 10958
    stack_size: 29
    reductions: 14371
  neighbours:


</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during standard_io in peer_SUITE 2024-03-04 18:16:02.983 ***</b>
=WARNING REPORT==== 4-Mar-2024::18:16:01.981735 ===
Process <0.87.0> on node 'peer_SUITE-shutdown_stop-395429-11805@f307f798be6e' enabled access to the emulator internal state.
NOTE: This is an erts internal test feature and should *only* be used by OTP test-suites.



</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during standard_io in peer_SUITE 2024-03-04 18:16:03.186 ***</b>
=WARNING REPORT==== 4-Mar-2024::18:16:02.184255 ===
Process <0.87.0> on node 'peer_SUITE-shutdown_halt-496418-11805@f307f798be6e' enabled access to the emulator internal state.
NOTE: This is an erts internal test feature and should *only* be used by OTP test-suites.



</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during standard_io in peer_SUITE 2024-03-04 18:16:03.367 ***</b>
=WARNING REPORT==== 4-Mar-2024::18:16:03.367162 ===
peer:stop() timed out waiting for disconnect from node 'init_debug-411684-11805@f307f798be6e'. The connection was forcefully taken down.

</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during standard_io in peer_SUITE 2024-03-04 18:16:03.732 ***</b>
=WARNING REPORT==== 4-Mar-2024::18:16:03.732107 ===
peer:stop() timed out waiting for disconnect from node 'peer_SUITE-shutdown_stop_timeout-395365-11805@f307f798be6e'. The connection was forcefully taken down.

</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during standard_io in peer_SUITE 2024-03-04 18:16:03.778 ***</b>
=WARNING REPORT==== 4-Mar-2024::18:16:03.778094 ===
peer:stop() timed out waiting for disconnect from node 'peer_SUITE-shutdown_halt_timeout-455299-11805@f307f798be6e'. The connection was forcefully taken down.

</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during standard_io in peer_SUITE 2024-03-04 18:16:04.802 ***</b>
=ERROR REPORT==== 4-Mar-2024::18:16:04.801935 ===
** Generic server <0.255756.0> terminating 
** Last message in was {'EXIT',<0.255707.0>,
                           {#Ref<0.2190842303.2221670401.170674>,4192057,ok,
                            [{peer_SUITE,
                                 cntrl_channel_handler_crash_old_release}],
                            []}}
** When Server state == {peer_state,#{args =>
                                          ["-setcookie",
                                           "BCOEVRDWHNLSGOIYIJHI","-pa",
                                           "/buildroot/otp/lib/stdlib/make_test_dir/stdlib_test",
                                           "-env","ERL_CRASH_DUMP",
                                           "/buildroot/otp/lib/stdlib/make_test_dir/ct_logs/ct_run.test_server@f307f798be6e.2024-03-04_18.00.23/erl_crash_dump.peer_SUITE-cntrl_channel_handler_crash_old_release-496322-11805",
                                           "-pa",
                                           "/buildroot/otp/lib/stdlib/make_test_dir/ct_logs/ct_run.test_server@f307f798be6e.2024-03-04_18.00.23/make_test_dir.stdlib_test.logs/run.2024-03-04_18.00.58/log_private/"],
                                      env => [{"ERL_AFLAGS",false}],
                                      name =>
                                          "peer_SUITE-cntrl_channel_handler_crash_old_release-496322-11805",
                                      connection => standard_io,
                                      exec =>
                                          "/usr/local/lib/erlang-25.3.2.9/bin/erl",
                                      start_cover => false},
                                    'peer_SUITE-cntrl_channel_handler_crash_old_release-496322-11805@f307f798be6e',
                                    "/usr/local/lib/erlang-25.3.2.9/bin/erl",
                                    ["-sname",
                                     "peer_SUITE-cntrl_channel_handler_crash_old_release-496322-11805",
                                     "-setcookie","BCOEVRDWHNLSGOIYIJHI",
                                     "-pa",
                                     "/buildroot/otp/lib/stdlib/make_test_dir/stdlib_test",
                                     "-env","ERL_CRASH_DUMP",
                                     "/buildroot/otp/lib/stdlib/make_test_dir/ct_logs/ct_run.test_server@f307f798be6e.2024-03-04_18.00.23/erl_crash_dump.peer_SUITE-cntrl_channel_handler_crash_old_release-496322-11805",
                                     "-pa",
                                     "/buildroot/otp/lib/stdlib/make_test_dir/ct_logs/ct_run.test_server@f307f798be6e.2024-03-04_18.00.23/make_test_dir.stdlib_test.logs/run.2024-03-04_18.00.58/log_private/",
                                     "-user","peer"],
                                    #Port<0.3126>,undefined,<<>>,running,
                                    {<0.255707.0>,
                                     #Ref<0.2190842303.2213806084.7226>},
                                    0,#{}}
** Reason for termination ==
** {#Ref<0.2190842303.2221670401.170674>,4192057,ok,
    [{peer_SUITE,cntrl_channel_handler_crash_old_release}],
    []}


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during standard_io in peer_SUITE 2024-03-04 18:16:04.803 ***</b>
=CRASH REPORT==== 4-Mar-2024::18:16:04.802663 ===
  crasher:
    initial call: peer:init/1
    pid: <0.255756.0>
    registered_name: []
    exception exit: {#Ref<0.2190842303.2221670401.170674>,4192057,ok,
                     [{peer_SUITE,cntrl_channel_handler_crash_old_release}],
                     []}
      in function  gen_server:decode_msg/9 (gen_server.erl, line 2129)
    ancestors: [<0.255707.0>]
    message_queue_len: 1
    messages: [{'EXIT',#Port<0.3126>,normal}]
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 17731
    stack_size: 29
    reductions: 18955
  neighbours:


</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during supervisor_SUITE:temporary_bystander/1 2024-03-04 18:27:25.935 ***</b>
=ERROR REPORT==== 4-Mar-2024::18:27:25.935444 ===
** Generic server <0.301994.0> terminating 
** Last message in was {'EXIT',<0.301992.0>,
                               {#Ref<0.2190842303.2258370561.53923>,350647,
                                [{child1,<0.302001.0>,worker,[]}],
                                [{supervisor_SUITE,temporary_bystander}],
                                []}}
** When Server state == {state,
                            {<0.301994.0>,supervisor_SUITE},
                            one_for_all,
                            {[child1],
                             #{child1 =>
                                   {child,<0.302000.0>,child1,
                                       {supervisor_1,start_child,[]},
                                       permanent,false,100,worker,[]}}},
                            undefined,2,300,
                            [-576459130],
                            0,never,supervisor_SUITE,
                            {ok,{{one_for_all,2,300},[]}}}
** Reason for termination ==
** {#Ref<0.2190842303.2258370561.53923>,350647,
    [{child1,<0.302001.0>,worker,[]}],
    [{supervisor_SUITE,temporary_bystander}],
    []}


</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during supervisor_SUITE:temporary_bystander/1 2024-03-04 18:27:25.935 ***</b>
=ERROR REPORT==== 4-Mar-2024::18:27:25.935450 ===
** Generic server <0.301995.0> terminating 
** Last message in was {'EXIT',<0.301992.0>,
                               {#Ref<0.2190842303.2258370561.53923>,350647,
                                [{child1,<0.302001.0>,worker,[]}],
                                [{supervisor_SUITE,temporary_bystander}],
                                []}}
** When Server state == {state,
                            {<0.301995.0>,supervisor_SUITE},
                            rest_for_one,
                            {[child1],
                             #{child1 =>
                                   {child,<0.302001.0>,child1,
                                       {supervisor_1,start_child,[]},
                                       permanent,false,100,worker,[]}}},
                            undefined,2,300,
                            [-576459130],
                            0,never,supervisor_SUITE,
                            {ok,{{rest_for_one,2,300},[]}}}
** Reason for termination ==
** {#Ref<0.2190842303.2258370561.53923>,350647,
    [{child1,<0.302001.0>,worker,[]}],
    [{supervisor_SUITE,temporary_bystander}],
    []}


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during supervisor_SUITE:temporary_bystander/1 2024-03-04 18:27:25.936 ***</b>
=CRASH REPORT==== 4-Mar-2024::18:27:25.935993 ===
  crasher:
    initial call: supervisor:supervisor_SUITE/1
    pid: <0.301994.0>
    registered_name: []
    exception exit: {#Ref<0.2190842303.2258370561.53923>,350647,
                     [{child1,<0.302001.0>,worker,[]}],
                     [{supervisor_SUITE,temporary_bystander}],
                     []}
      in function  gen_server:decode_msg/9 (gen_server.erl, line 2129)
    ancestors: [<0.301992.0>]
    message_queue_len: 0
    messages: []
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 2586
    stack_size: 29
    reductions: 11912
  neighbours:


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during supervisor_SUITE:temporary_bystander/1 2024-03-04 18:27:25.937 ***</b>
=CRASH REPORT==== 4-Mar-2024::18:27:25.936032 ===
  crasher:
    initial call: supervisor:supervisor_SUITE/1
    pid: <0.301995.0>
    registered_name: []
    exception exit: {#Ref<0.2190842303.2258370561.53923>,350647,
                     [{child1,<0.302001.0>,worker,[]}],
                     [{supervisor_SUITE,temporary_bystander}],
                     []}
      in function  gen_server:decode_msg/9 (gen_server.erl, line 2129)
    ancestors: [<0.301992.0>]
    message_queue_len: 0
    messages: []
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 2586
    stack_size: 29
    reductions: 11935
  neighbours:


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during supervisor_bridge_SUITE:simple_global_supervisor/1 2024-03-04 18:28:09.405 ***</b>
=CRASH REPORT==== 4-Mar-2024::18:28:09.405378 ===
  crasher:
    initial call: supervisor_bridge:supervisor_bridge_SUITE/1
    pid: <0.402152.0>
    registered_name: []
    exception exit: killed
      in function  gen_server:decode_msg/9 (gen_server.erl, line 2129)
    ancestors: [bridge9212,<0.402147.0>]
    message_queue_len: 0
    messages: []
    links: [<0.402153.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 2586
    stack_size: 29
    reductions: 4113
  neighbours:
    neighbour:
      pid: <0.402153.0>
      registered_name: work_supervisor_bridge_SUITE_server
      initial_call: {supervisor_bridge_SUITE,internal_loop_init,1}
      current_function: {supervisor_bridge_SUITE,internal_loop,1}
      ancestors: []
      message_queue_len: 0
      links: [<0.402152.0>]
      trap_exit: false
      status: waiting
      heap_size: 233
      stack_size: 3
      reductions: 9
      current_stacktrace: [{supervisor_bridge_SUITE,internal_loop,1,
                      [{file,"supervisor_bridge_SUITE.erl"},{line,152}]}]

</pre></div>
<pre>
</pre>
<center>
<br /><hr /><p>
<a href="../../../all_runs.html">Test run history
</a>  |  <a href="../../../index.html">Top level test index
</a>  |  <a href="../../../suite.log.latest.html">Latest test result</a>
</p>
<div class="copyright">Copyright &copy; 2024 <a href="http://www.erlang.org">Open Telecom Platform</a><br />
Updated: <!--date-->Mon Mar 04 2024 18:00:58<!--/date--><br />
</div>
</center>
</body>
</html>
