<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>Test init_SUITE:restart_with_mode result</title>
<meta http-equiv="cache-control" content="no-cache"></meta>
<meta http-equiv="content-type" content="text/html; charset=utf-8"></meta>
<link rel="stylesheet" href="../../ct_default.css" type="text/css"></link>
<script type="text/javascript" src="../../jquery-latest.js"></script>
<script type="text/javascript" src="../../jquery.tablesorter.min.js"></script>
</head>
<body>

<a name="top"></a><pre>
=== Test case: <a href="init_suite.src.html#restart_with_mode-1">init_SUITE:restart_with_mode/1</a> (click for source code)

=== Config value:

    [{watchdog,&lt;0.115776.0&gt;},
     {tc_logfile,"/buildroot/otp/lib/kernel/make_test_dir/ct_logs/ct_run.test_server@de3f76024203.2024-11-26_17.05.44/make_test_dir.kernel_test.logs/run.2024-11-26_17.06.12/init_suite.restart_with_mode.html"},
     {tc_group_properties,[]},
     {tc_group_path,[]},
     {data_dir,"/buildroot/otp/lib/kernel/make_test_dir/kernel_test/init_SUITE_data/"},
     {priv_dir,"/buildroot/otp/lib/kernel/make_test_dir/ct_logs/ct_run.test_server@de3f76024203.2024-11-26_17.05.44/make_test_dir.kernel_test.logs/run.2024-11-26_17.06.12/log_private/"},
     {nodenames,[]}]

=== Current directory is "/buildroot/otp/lib/kernel/make_test_dir/ct_logs/ct_run.test_server@de3f76024203.2024-11-26_17.05.44"

=== Started at 2024-11-26 17:44:58

<br />

</pre>
<div class="ct_error_notify"><pre><b>*** CT Error Notification 2024-11-26 17:45:10.497 ***</b><a id=e-7617 class="link-to-entry" href="#e-7617">&#x1f517;</a>
init_SUITE:restart_with_mode failed on line 373
Reason: {badmatch,"interactive=ERROR REPORT==== 26-Nov-2024::17:44:5...}

<a href="#end">Full error description and stacktrace</a>
</pre></div>
<pre>
<a name="end"></a>


=== Ended at 2024-11-26 17:45:10
=== Location: [{init_SUITE,restart_with_mode,<a href="init_suite.src.html#373">373</a>},
              {test_server,ts_tc,1794},
              {test_server,run_test_case_eval1,1303},
              {test_server,run_test_case_eval,1235}]
=== === Reason: no match of right hand side value "interactive=ERROR REPORT==== 26-Nov-2024::17:44:59.751673 ===\nError in process &lt;0.297.0&gt; with exit value:\n{undef,[{prim_tty,init,\n                  [#{input =&gt; disabled,output =&gt; cooked,ofd =&gt; stderr}],\n                  []},\n        {standard_error,server,0,[{file,\"standard_error.erl\"},{line,67}]}]}\n\n=SUPERVISOR REPORT==== 26-Nov-2024::17:44:59.751734 ===\n    supervisor: {local,standard_error_sup}\n    errorContext: child_terminated\n    reason: {undef,[{prim_tty,init,\n                              [#{input =&gt; disabled,output =&gt; cooked,\n                                 ofd =&gt; stderr}],\n                              []},\n                    {standard_error,server,0,\n                                    [{file,\"standard_error.erl\"},{line,67}]}]}\n    offender: [{pid,&lt;0.297.0&gt;},{mod,standard_error}]\n\n=ERROR REPORT==== 26-Nov-2024::17:44:59.751967 ===\n** Generic server standard_error_sup terminating \n** Last message in was {'EXIT',&lt;0.297.0&gt;,\n                           {undef,\n                               [{prim_tty,init,\n                                    [#{input =&gt; disabled,output =&gt; cooked,\n                                       ofd =&gt; stderr}],\n                                    []},\n                                {standard_error,server,0,\n                                    [{file,\"standard_error.erl\"},\n                                     {line,67}]}]}}\n** When Server state == {state,standard_error,undefined,&lt;0.297.0&gt;,\n                               {local,standard_error_sup}}\n** Reason for termination ==\n** {'function not exported',\n       [{prim_tty,init,\n            [#{input =&gt; disabled,output =&gt; cooked,ofd =&gt; stderr}],\n            []},\n        {standard_error,server,0,[{file,\"standard_error.erl\"},{line,67}]}]}\n\n=CRASH REPORT==== 26-Nov-2024::17:44:59.752030 ===\n  crasher:\n    initial call: supervisor_bridge:standard_error/1\n    pid: &lt;0.296.0&gt;\n    registered_name: standard_error_sup\n    exception exit: {undef,\n                        [{prim_tty,init,\n                             [#{input =&gt; disabled,output =&gt; cooked,\n                                ofd =&gt; stderr}],\n                             []},\n                         {standard_error,server,0,\n                             [{file,\"standard_error.erl\"},{line,67}]}]}\n      in function  gen_server:handle_common_reply/8 (gen_server.erl, line 2476)\n    ancestors: [kernel_sup,&lt;0.292.0&gt;]\n    message_queue_len: 0\n    messages: []\n    links: [&lt;0.294.0&gt;]\n    dictionary: []\n    trap_exit: true\n    status: running\n    heap_size: 610\n    stack_size: 29\n    reductions: 360\n  neighbours:\n\n=ERROR REPORT==== 26-Nov-2024::17:44:59.755244 ===\n** State machine user_drv terminating\n** When server state  = {undefined,undefined}\n** Reason for termination = error:{badmatch,{error,arguments}}\n** Callback modules = [user_drv]\n** Callback mode = state_functions\n** Stacktrace =\n**  [{user_drv,init_standard_error,2,[{file,\"user_drv.erl\"},{line,208}]},\n     {user_drv,init,1,[{file,\"user_drv.erl\"},{line,184}]},\n     {gen_statem,init_it,6,[{file,\"gen_statem.erl\"},{line,3312}]},\n     {proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,329}]}]\n\n=CRASH REPORT==== 26-Nov-2024::17:44:59.755426 ===\n  crasher:\n    initial call: user_drv:init/1\n    pid: &lt;0.316.0&gt;\n    registered_name: []\n    exception error: no match of right hand side value {error,arguments}\n      in function  user_drv:init_standard_error/2 (user_drv.erl, line 208)\n      in call from user_drv:init/1 (user_drv.erl, line 184)\n      in call from gen_statem:init_it/6 (gen_statem.erl, line 3312)\n    ancestors: [&lt;0.315.0&gt;,kernel_sup,&lt;0.292.0&gt;]\n    message_queue_len: 0\n    messages: []\n    links: [&lt;0.317.0&gt;,&lt;0.318.0&gt;]\n    dictionary: []\n    trap_exit: true\n    status: running\n    heap_size: 610\n    stack_size: 29\n    reductions: 308\n  neighbours:\n    neighbour:\n      pid: &lt;0.318.0&gt;\n      registered_name: user_drv_reader\n      initial call: prim_tty:reader/1\n      current_function: {prim_tty,reader_loop,2}\n      ancestors: [user_drv,&lt;0.315.0&gt;,kernel_sup,&lt;0.292.0&gt;]\n      message_queue_len: 0\n      links: [&lt;0.316.0&gt;]\n      trap_exit: false\n      status: waiting\n      heap_size: 233\n      stack_size: 12\n      reductions: 40\n      current_stacktrace: [{prim_tty,reader_loop,2,[{file,\"prim_tty.erl\"},{line,558}]},\n                  {proc_lib,init_p_do_apply,3,\n                            [{file,\"proc_lib.erl\"},{line,329}]}]\n    neighbour:\n      pid: &lt;0.317.0&gt;\n      registered_name: user_drv_writer\n      initial call: prim_tty:writer/1\n      current_function: {prim_tty,writer_loop,2}\n      ancestors: [user_drv,&lt;0.315.0&gt;,kernel_sup,&lt;0.292.0&gt;]\n      message_queue_len: 0\n      links: [&lt;0.316.0&gt;]\n      trap_exit: false\n      status: waiting\n      heap_size: 233\n      stack_size: 8\n      reductions: 24\n      current_stacktrace: [{prim_tty,writer_loop,2,[{file,\"prim_tty.erl\"},{line,657}]},\n                  {proc_lib,init_p_do_apply,3,\n                            [{file,\"proc_lib.erl\"},{line,329}]}]\n=CRASH REPORT==== 26-Nov-2024::17:45:09.854834 ===\n  crasher:\n    initial call: supervisor_bridge:user_sup/1\n    pid: &lt;0.315.0&gt;\n    registered_name: []\n    exception exit: nouser\n      in function  gen_server:init_it/6 (gen_server.erl, line 2210)\n    ancestors: [kernel_sup,&lt;0.292.0&gt;]\n    message_queue_len: 0\n    messages: []\n    links: [&lt;0.294.0&gt;]\n    dictionary: []\n    trap_exit: true\n    status: running\n    heap_size: 610\n    stack_size: 29\n    reductions: 353\n  neighbours:\n\n=SUPERVISOR REPORT==== 26-Nov-2024::17:45:09.854895 ===\n    supervisor: {local,kernel_sup}\n    errorContext: start_error\n    reason: nouser\n    offender: [{pid,undefined},\n               {id,user},\n               {mfargs,{user_sup,start,[]}},\n               {restart_type,temporary},\n               {significant,false},\n               {shutdown,2000},\n               {child_type,supervisor}]\n\n=SUPERVISOR REPORT==== 26-Nov-2024::17:45:09.855551 ===\n    supervisor: {local,kernel_sup}\n    errorContext: shutdown_error\n    reason: {undef,[{prim_tty,init,\n                              [#{input =&gt; disabled,output =&gt; cooked,\n                                 ofd =&gt; stderr}],\n                              []},\n                    {standard_error,server,0,\n                                    [{file,\"standard_error.erl\"},{line,67}]}]}\n    offender: [{pid,&lt;0.296.0&gt;},\n               {id,standard_error},\n               {mfargs,{standard_error,start_link,[]}},\n               {restart_type,temporary},\n               {significant,false},\n               {shutdown,2000},\n               {child_type,supervisor}]\n\n=CRASH REPORT==== 26-Nov-2024::17:45:09.855874 ===\n  crasher:\n    initial call: application_master:init/3\n    pid: &lt;0.291.0&gt;\n    registered_name: []\n    exception exit: {{shutdown,{failed_to_start_child,user,nouser}},\n                     {kernel,start,[normal,[]]}}\n      in function  application_master:init/3 (application_master.erl, line 143)\n    ancestors: [application_controller,&lt;0.87.0&gt;]\n    message_queue_len: 1\n    messages: [{'EXIT',&lt;0.292.0&gt;,normal}]\n    links: [&lt;0.290.0&gt;]\n    dictionary: []\n    trap_exit: true\n    status: running\n    heap_size: 233\n    stack_size: 29\n    reductions: 63\n  neighbours:\n\n=INFO REPORT==== 26-Nov-2024::17:45:09.855907 ===\n    application: kernel\n    exited: {{shutdown,{failed_to_start_child,user,nouser}},\n             {kernel,start,[normal,[]]}}\n    type: permanent\n\nKernel pid terminated (application_controller) (\"{application_start_failure,kernel,{{shutdown,{failed_to_start_child,user,nouser}},{kernel,start,[normal,[]]}}}\")\r\n\r\nCrash dump is being written to: /buildroot/otp/lib/kernel/make_test_dir/kernel_erl_crash.dump...done\r\n"
  in function  init_SUITE:restart_with_mode/1 (init_SUITE.erl, line 373)
  in call from test_server:ts_tc/3 (test_server.erl, line 1794)
  in call from test_server:run_test_case_eval1/6 (test_server.erl, line 1303)
  in call from test_server:run_test_case_eval/9 (test_server.erl, line 1235)
</pre>
<center>
<br /><hr /><p>
<a href="../../../all_runs.html">Test run history
</a>  |  <a href="../../../index.html">Top level test index
</a>  |  <a href="../../../suite.log.latest.html">Latest test result</a>
</p>
<div class="copyright">Copyright &copy; 2024 <a href="http://www.erlang.org">Open Telecom Platform</a><br />
Updated: <!--date-->Tue Nov 26 2024 17:44:58<!--/date--><br />
</div>
</center>
</body>
</html>
