=== Suite started at 2024-11-25 08:26:09
=== Starting test, 4 test cases
=cases         4
=user          otptest
=host          c3276ca3fbc7
=hosts         c3276ca3fbc7 
=emulator_vsn  15.1.2
=emulator      beam
=otp_release   28
=started       2024-11-25 08:26:09
=case          config_func_error_1_SUITE:init_per_suite
=logfile       config_func_error_1_suite.init_per_suite.html
=started       2024-11-25 08:26:09
=ended         2024-11-25 08:26:09
=result        ok
=elapsed       0.000000s
=case          config_func_error_1_SUITE:exit_in_iptc
=logfile       config_func_error_1_suite.exit_in_iptc.html
=started       2024-11-25 08:26:09
=== ERROR! config_func_error_1_SUITE:init_per_testcase(exit_in_iptc, [{watchdog,
                                                                   <0.3719.0>},
                                                                  {tc_logfile,
                                                                   "/buildroot/otp/lib/common_test/make_test_dir/ct_logs/ct_run.test_server@c3276ca3fbc7.2024-11-25_08.14.36/make_test_dir.common_test_test.logs/run.2024-11-25_08.14.38/log_private/ct_run.ct@c3276ca3fbc7.2024-11-25_08.26.08/ct_error_SUITE_data.error.config_func_error_1_SUITE.logs/run.2024-11-25_08.26.09/config_func_error_1_suite.exit_in_iptc.html"},
                                                                  {tc_group_properties,
                                                                   []},
                                                                  {tc_group_path,
                                                                   []},
                                                                  {data_dir,
                                                                   "/buildroot/otp/lib/common_test/make_test_dir/common_test_test/ct_error_SUITE_data/error/test/config_func_error_1_SUITE_data/"},
                                                                  {priv_dir,
                                                                   "/buildroot/otp/lib/common_test/make_test_dir/ct_logs/ct_run.test_server@c3276ca3fbc7.2024-11-25_08.14.36/make_test_dir.common_test_test.logs/run.2024-11-25_08.14.38/log_private/ct_run.ct@c3276ca3fbc7.2024-11-25_08.26.08/ct_error_SUITE_data.error.config_func_error_1_SUITE.logs/run.2024-11-25_08.26.09/log_private/"}]) failed!
	Reason: {'EXIT',{badfun,<0.3721.0>}}

=ended         2024-11-25 08:26:09
=result        auto_skipped: {failed,
                                 {config_func_error_1_SUITE,
                                     init_per_testcase,
                                     {'EXIT',{badfun,<0.3721.0>}}}}
=elapsed       0.000000s
=== *** SKIPPED test case 1 of 4 ***
=case          config_func_error_1_SUITE:exit_in_eptc
=logfile       config_func_error_1_suite.exit_in_eptc.html
=started       2024-11-25 08:26:09
=== WARNING! config_func_error_1_SUITE:end_per_testcase(exit_in_eptc, [{tc_status,
                                                                    ok},
                                                                   {watchdog,
                                                                    <0.3725.0>},
                                                                   {tc_logfile,
                                                                    "/buildroot/otp/lib/common_test/make_test_dir/ct_logs/ct_run.test_server@c3276ca3fbc7.2024-11-25_08.14.36/make_test_dir.common_test_test.logs/run.2024-11-25_08.14.38/log_private/ct_run.ct@c3276ca3fbc7.2024-11-25_08.26.08/ct_error_SUITE_data.error.config_func_error_1_SUITE.logs/run.2024-11-25_08.26.09/config_func_error_1_suite.exit_in_eptc.html"},
                                                                   {tc_group_properties,
                                                                    []},
                                                                   {tc_group_path,
                                                                    []},
                                                                   {data_dir,
                                                                    "/buildroot/otp/lib/common_test/make_test_dir/common_test_test/ct_error_SUITE_data/error/test/config_func_error_1_SUITE_data/"},
                                                                   {priv_dir,
                                                                    "/buildroot/otp/lib/common_test/make_test_dir/ct_logs/ct_run.test_server@c3276ca3fbc7.2024-11-25_08.14.36/make_test_dir.common_test_test.logs/run.2024-11-25_08.14.38/log_private/ct_run.ct@c3276ca3fbc7.2024-11-25_08.26.08/ct_error_SUITE_data.error.config_func_error_1_SUITE.logs/run.2024-11-25_08.26.09/log_private/"}]) failed!
	Reason: {'EXIT',{nocatch,generated_throw}}

=ended         2024-11-25 08:26:09
=result        ok
=elapsed       0.000000s
=case          config_func_error_1_SUITE:init_per_group
=logfile       config_func_error_1_suite.init_per_group.html
=group_props   [{name,g1}]
=started       2024-11-25 08:26:09
=ended         2024-11-25 08:26:09
=result        ok
=elapsed       0.000000s
=case          config_func_error_1_SUITE:exit_in_iptc
=logfile       config_func_error_1_suite.exit_in_iptc.7586.html
=started       2024-11-25 08:26:09
=== ERROR! config_func_error_1_SUITE:init_per_testcase(exit_in_iptc, [{watchdog,
                                                                   <0.3732.0>},
                                                                  {tc_logfile,
                                                                   "/buildroot/otp/lib/common_test/make_test_dir/ct_logs/ct_run.test_server@c3276ca3fbc7.2024-11-25_08.14.36/make_test_dir.common_test_test.logs/run.2024-11-25_08.14.38/log_private/ct_run.ct@c3276ca3fbc7.2024-11-25_08.26.08/ct_error_SUITE_data.error.config_func_error_1_SUITE.logs/run.2024-11-25_08.26.09/config_func_error_1_suite.exit_in_iptc.7586.html"},
                                                                  {tc_group_properties,
                                                                   [{name,
                                                                     g1}]},
                                                                  {tc_group_path,
                                                                   []},
                                                                  {data_dir,
                                                                   "/buildroot/otp/lib/common_test/make_test_dir/common_test_test/ct_error_SUITE_data/error/test/config_func_error_1_SUITE_data/"},
                                                                  {priv_dir,
                                                                   "/buildroot/otp/lib/common_test/make_test_dir/ct_logs/ct_run.test_server@c3276ca3fbc7.2024-11-25_08.14.36/make_test_dir.common_test_test.logs/run.2024-11-25_08.14.38/log_private/ct_run.ct@c3276ca3fbc7.2024-11-25_08.26.08/ct_error_SUITE_data.error.config_func_error_1_SUITE.logs/run.2024-11-25_08.26.09/log_private/"}]) failed!
	Reason: {'EXIT',{undef,{ct_test_support,random_error,[],[]}}}

=ended         2024-11-25 08:26:09
=result        auto_skipped: {failed,
                              {config_func_error_1_SUITE,init_per_testcase,
                               {'EXIT',
                                {undef,
                                 {ct_test_support,random_error,[],[]}}}}}
=elapsed       0.000000s
=== *** SKIPPED test case 3 of 4 ***
=case          config_func_error_1_SUITE:end_per_group
=logfile       config_func_error_1_suite.end_per_group.html
=group_props   [{name,g1}]
=started       2024-11-25 08:26:09
=ended         2024-11-25 08:26:09
=result        ok
=elapsed       0.000000s
=group_time    0.057s
=case          config_func_error_1_SUITE:init_per_group
=logfile       config_func_error_1_suite.init_per_group.963.html
=group_props   [{name,g2}]
=started       2024-11-25 08:26:09
=ended         2024-11-25 08:26:09
=result        ok
=elapsed       0.000000s
=case          config_func_error_1_SUITE:exit_in_eptc
=logfile       config_func_error_1_suite.exit_in_eptc.995.html
=started       2024-11-25 08:26:09
=== WARNING! config_func_error_1_SUITE:end_per_testcase(exit_in_eptc, [{tc_status,
                                                                    ok},
                                                                   {watchdog,
                                                                    <0.3741.0>},
                                                                   {tc_logfile,
                                                                    "/buildroot/otp/lib/common_test/make_test_dir/ct_logs/ct_run.test_server@c3276ca3fbc7.2024-11-25_08.14.36/make_test_dir.common_test_test.logs/run.2024-11-25_08.14.38/log_private/ct_run.ct@c3276ca3fbc7.2024-11-25_08.26.08/ct_error_SUITE_data.error.config_func_error_1_SUITE.logs/run.2024-11-25_08.26.09/config_func_error_1_suite.exit_in_eptc.995.html"},
                                                                   {tc_group_properties,
                                                                    [{name,
                                                                      g2}]},
                                                                   {tc_group_path,
                                                                    []},
                                                                   {data_dir,
                                                                    "/buildroot/otp/lib/common_test/make_test_dir/common_test_test/ct_error_SUITE_data/error/test/config_func_error_1_SUITE_data/"},
                                                                   {priv_dir,
                                                                    "/buildroot/otp/lib/common_test/make_test_dir/ct_logs/ct_run.test_server@c3276ca3fbc7.2024-11-25_08.14.36/make_test_dir.common_test_test.logs/run.2024-11-25_08.14.38/log_private/ct_run.ct@c3276ca3fbc7.2024-11-25_08.26.08/ct_error_SUITE_data.error.config_func_error_1_SUITE.logs/run.2024-11-25_08.26.09/log_private/"}]) failed!
	Reason: {'EXIT',
                    {badarg,
                        {erlang,send,
                            [undef_proc,hello],
                            [{error_info,#{module => erl_erts_errors}}]}}}

=ended         2024-11-25 08:26:09
=result        ok
=elapsed       0.000000s
=case          config_func_error_1_SUITE:end_per_group
=logfile       config_func_error_1_suite.end_per_group.1059.html
=group_props   [{name,g2}]
=started       2024-11-25 08:26:09
=ended         2024-11-25 08:26:09
=result        ok
=elapsed       0.000000s
=group_time    0.057s
=case          config_func_error_1_SUITE:end_per_suite
=logfile       config_func_error_1_suite.end_per_suite.html
=started       2024-11-25 08:26:09
=ended         2024-11-25 08:26:09
=result        ok
=elapsed       0.000000s
=group_time    0.259s
=== TEST COMPLETE, 2 ok, 0 failed, 2 skipped of 4 test cases

=finished      2024-11-25 08:26:09
=failed        0
=successful    2
=user_skipped  0
=auto_skipped  2
=elapsed_time  316432
