<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>Unexpected I/O log</title>
<meta http-equiv="cache-control" content="no-cache"></meta>
<meta http-equiv="content-type" content="text/html; charset=utf-8"></meta>
<link rel="stylesheet" href="../../ct_default.css" type="text/css"></link>
<script type="text/javascript" src="../../jquery-latest.js"></script>
<script type="text/javascript" src="../../jquery.tablesorter.min.js"></script>
</head>
<body>

<br />
<h3>Unexpected I/O</h3>
<pre>

</pre>
<div class="error_logger"><pre><b>*** System report during multi_call_parallel in gen_server_SUITE 2025-01-28 10:44:55.503 ***</b>
=ERROR REPORT==== 28-Jan-2025::10:44:55.503211 ===
** Generic server my_test_name terminating 
** Last message in was stop
** When Server state == {formatted,[]}
** Reason for termination ==
** stopped
** Client <0.247064.0> stacktrace
** [{gen_server,mc_recv,5,[{file,"gen_server.erl"},{line,1975}]},
    {gen_server,multi_call,4,[{file,"gen_server.erl"},{line,1936}]},
    {gen_server_SUITE,multicall,1,[{file,"gen_server_SUITE.erl"},{line,1487}]},
    {test_server,ts_tc,3,[{file,"test_server.erl"},{line,1794}]},
    {test_server,run_test_case_eval1,6,[{file,"test_server.erl"},{line,1303}]},
    {test_server,run_test_case_eval,9,[{file,"test_server.erl"},{line,1235}]}]


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during multi_call_parallel in gen_server_SUITE 2025-01-28 10:44:55.503 ***</b>
=CRASH REPORT==== 28-Jan-2025::10:44:55.503534 ===
  crasher:
    initial call: gen_server_SUITE:init/1
    pid: <0.247068.0>
    registered_name: my_test_name
    exception exit: stopped
      in function  gen_server:handle_msg/6 (gen_server.erl, line 2428)
    ancestors: [<0.247064.0>]
    message_queue_len: 0
    messages: []
    links: [<0.247064.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 987
    stack_size: 29
    reductions: 594
  neighbours:


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during gen_server_SUITE:spec_init/1 2025-01-28 10:45:35.417 ***</b>
=ERROR REPORT==== 28-Jan-2025::10:45:35.417775 ===
** Generic server hurra terminating 
** Last message in was {'EXIT',&lt;0.251412.0&gt;,
                               {#Ref&lt;0.2994499957.3587964929.45531&gt;,1003980,
                                ok,
                                [{gen_server_SUITE,spec_init}],
                                []}}
** When Server state == {formatted,{}}
** Reason for termination ==
** {#Ref&lt;0.2994499957.3587964929.45531&gt;,1003980,ok,
    [{gen_server_SUITE,spec_init}],
    []}


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during gen_server_SUITE:spec_init/1 2025-01-28 10:45:35.418 ***</b>
=CRASH REPORT==== 28-Jan-2025::10:45:35.418039 ===
  crasher:
    initial call: gen_server_SUITE:spec_init_global_default_timeout/2
    pid: &lt;0.251432.0&gt;
    registered_name: []
    exception exit: {#Ref&lt;0.2994499957.3587964929.45531&gt;,1003980,ok,
                     [{gen_server_SUITE,spec_init}],
                     []}
      in function  gen_server:decode_msg/9 (gen_server.erl, line 2301)
    ancestors: [&lt;0.251412.0&gt;]
    message_queue_len: 0
    messages: []
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 29
    reductions: 414
  neighbours:


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during log_mf_h_SUITE:test/1 2025-01-28 10:50:17.732 ***</b>
=CRASH REPORT==== 28-Jan-2025::10:50:17.732501 ===
  crasher:
    initial call: gen_event:init_it/6
    pid: &lt;0.257252.0&gt;
    registered_name: []
    exception exit: {#Ref&lt;0.2994499957.3589275649.186267&gt;,6811,
                     {ok,3},
                     [{log_mf_h_SUITE,test}],
                     []}
      in function  gen_event:terminate_server/4 (gen_event.erl, line 1696)
    ancestors: [&lt;0.257250.0&gt;]
    message_queue_len: 0
    messages: []
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 6772
    stack_size: 29
    reductions: 28120
  neighbours:


</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during dist in peer_SUITE 2025-01-28 10:50:26.919 ***</b>
=ERROR REPORT==== 28-Jan-2025::10:50:26.919442 ===
** Generic server <0.258555.0> terminating 
** Last message in was {nodedown,'peer_down_crash-387845-11901@2173de9773d8'}
** When Server state == {peer_state,
                            #{args => ["-connect_all","false"],
                              name => "peer_down_crash-387845-11901",
                              peer_down => crash},
                            'peer_down_crash-387845-11901@2173de9773d8',
                            [47,98,117,105,108,100,114,111,111,116,47,111,116,
                             112,47,69,114,108,97,110,103,32,8709,8868,8478,
                             47,101,114,116,115,45,49,53,46,50,46,49,47,98,
                             105,110,47,101,114,108],
                            ["-sname","peer_down_crash-387845-11901",
                             "-connect_all","false","-detached",
                             "-peer_detached","-user","peer","-origin",
                             "g1h3GHRlc3Rfc2VydmVyQDIxNzNkZTk3NzNkOAAD8fsAAAAAZ5ikig=="],
                            undefined,undefined,<<>>,
                            {down,
                                {nodedown,
                                    'peer_down_crash-387845-11901@2173de9773d8'}},
                            {<0.258524.0>,#Ref<0.2994499957.3581935620.98291>},
                            0,#{}}
** Reason for termination ==
** {nodedown,'peer_down_crash-387845-11901@2173de9773d8'}


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during dist in peer_SUITE 2025-01-28 10:50:26.919 ***</b>
=CRASH REPORT==== 28-Jan-2025::10:50:26.919807 ===
  crasher:
    initial call: peer:init/1
    pid: <0.258555.0>
    registered_name: []
    exception exit: {nodedown,'peer_down_crash-387845-11901@2173de9773d8'}
      in function  gen_server:handle_common_reply/8 (gen_server.erl, line 2478)
    ancestors: [<0.258524.0>]
    message_queue_len: 0
    messages: []
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 1598
    stack_size: 29
    reductions: 1499
  neighbours:


</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during dist in peer_SUITE 2025-01-28 10:50:27.737 ***</b>
=WARNING REPORT==== 28-Jan-2025::10:50:26.736154 ===
Process <0.92.0> on node 'peer_SUITE-shutdown_halt-387909-11901@2173de9773d8' enabled access to the emulator internal state.
NOTE: This is an erts internal test feature and should *only* be used by OTP test-suites.



</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during dist in peer_SUITE 2025-01-28 10:50:27.778 ***</b>
=WARNING REPORT==== 28-Jan-2025::10:50:26.776479 ===
Process <0.92.0> on node 'peer_SUITE-shutdown_stop-428452-11901@2173de9773d8' enabled access to the emulator internal state.
NOTE: This is an erts internal test feature and should *only* be used by OTP test-suites.



</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during dist in peer_SUITE 2025-01-28 10:50:28.303 ***</b>
=WARNING REPORT==== 28-Jan-2025::10:50:28.303242 ===
peer:stop() timed out waiting for disconnect from node 'peer_SUITE-shutdown_stop_timeout-528994-11901@2173de9773d8'. The connection was forcefully taken down.

</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during dist in peer_SUITE 2025-01-28 10:50:28.453 ***</b>
=WARNING REPORT==== 28-Jan-2025::10:50:28.453130 ===
peer:stop() timed out waiting for disconnect from node 'peer_SUITE-shutdown_halt_timeout-387877-11901@2173de9773d8'. The connection was forcefully taken down.

</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during tcp in peer_SUITE 2025-01-28 10:50:43.965 ***</b>
=WARNING REPORT==== 28-Jan-2025::10:50:42.964181 ===
Process <0.89.0> on node 'peer_SUITE-shutdown_stop-388261-11901@2173de9773d8' enabled access to the emulator internal state.
NOTE: This is an erts internal test feature and should *only* be used by OTP test-suites.



</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during tcp in peer_SUITE 2025-01-28 10:50:44.290 ***</b>
=WARNING REPORT==== 28-Jan-2025::10:50:44.290240 ===
peer:stop() timed out waiting for disconnect from node 'peer_SUITE-shutdown_stop_timeout-408419-11901@2173de9773d8'. The connection was forcefully taken down.

</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during tcp in peer_SUITE 2025-01-28 10:50:44.399 ***</b>
=WARNING REPORT==== 28-Jan-2025::10:50:44.399118 ===
peer:stop() timed out waiting for disconnect from node 'peer_SUITE-shutdown_halt_timeout-388229-11901@2173de9773d8'. The connection was forcefully taken down.

</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during standard_io in peer_SUITE 2025-01-28 10:50:46.665 ***</b>
=ERROR REPORT==== 28-Jan-2025::10:50:46.665413 ===
** Generic server <0.258890.0> terminating 
** Last message in was {'EXIT',<0.258880.0>,
                               {#Ref<0.2994499957.3581935620.101095>,1611932,
                                ok,
                                [{peer_SUITE,cntrl_channel_handler_crash}],
                                []}}
** When Server state == {peer_state,#{name =>
                                          "peer_SUITE-cntrl_channel_handler_crash-388549-11901",
                                      connection => standard_io},
                                    'peer_SUITE-cntrl_channel_handler_crash-388549-11901@2173de9773d8',
                                    [47,98,117,105,108,100,114,111,111,116,47,
                                     111,116,112,47,69,114,108,97,110,103,32,
                                     8709,8868,8478,47,101,114,116,115,45,49,
                                     53,46,50,46,49,47,98,105,110,47,101,114,
                                     108],
                                    ["-sname",
                                     "peer_SUITE-cntrl_channel_handler_crash-388549-11901",
                                     "-user","peer"],
                                    #Port<0.3130>,undefined,<<>>,running,
                                    {<0.258880.0>,
                                     #Ref<0.2994499957.3581935620.101130>},
                                    0,#{}}
** Reason for termination ==
** {#Ref<0.2994499957.3581935620.101095>,1611932,ok,
    [{peer_SUITE,cntrl_channel_handler_crash}],
    []}


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during standard_io in peer_SUITE 2025-01-28 10:50:46.665 ***</b>
=CRASH REPORT==== 28-Jan-2025::10:50:46.665773 ===
  crasher:
    initial call: peer:init/1
    pid: <0.258890.0>
    registered_name: []
    exception exit: {#Ref<0.2994499957.3581935620.101095>,1611932,ok,
                     [{peer_SUITE,cntrl_channel_handler_crash}],
                     []}
      in function  gen_server:decode_msg/9 (gen_server.erl, line 2301)
    ancestors: [<0.258880.0>]
    message_queue_len: 1
    messages: [{'EXIT',#Port<0.3130>,normal}]
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 2586
    stack_size: 29
    reductions: 4500
  neighbours:


</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during standard_io in peer_SUITE 2025-01-28 10:50:47.194 ***</b>
=ERROR REPORT==== 28-Jan-2025::10:50:47.194083 ===
** Generic server <0.258926.0> terminating 
** Last message in was {'EXIT',<0.258879.0>,
                           {#Ref<0.2994499957.3581935620.101088>,2141607,ok,
                            [{peer_SUITE,
                                 cntrl_channel_handler_crash_old_release}],
                            []}}
** When Server state == {peer_state,#{args =>
                                          ["-setcookie",
                                           "YMZDXGBJWIOTSAJOUHND","-pa",
                                           "/buildroot/otp/lib/stdlib/make_test_dir/stdlib_test",
                                           "-env","ERL_CRASH_DUMP",
                                           "/buildroot/otp/lib/stdlib/make_test_dir/ct_logs/ct_run.test_server@2173de9773d8.2025-01-28_10.34.01/erl_crash_dump.peer_SUITE-cntrl_channel_handler_crash_old_release-429604-11901",
                                           "-pa",
                                           "/buildroot/otp/lib/stdlib/make_test_dir/ct_logs/ct_run.test_server@2173de9773d8.2025-01-28_10.34.01/make_test_dir.stdlib_test.logs/run.2025-01-28_10.34.36/log_private/"],
                                      env => [{"ERL_AFLAGS",false}],
                                      name =>
                                          "peer_SUITE-cntrl_channel_handler_crash_old_release-429604-11901",
                                      connection => standard_io,
                                      exec =>
                                          "/usr/local/lib/erlang-26.2.5.7/bin/erl",
                                      start_cover => false},
                                    'peer_SUITE-cntrl_channel_handler_crash_old_release-429604-11901@2173de9773d8',
                                    "/usr/local/lib/erlang-26.2.5.7/bin/erl",
                                    ["-sname",
                                     "peer_SUITE-cntrl_channel_handler_crash_old_release-429604-11901",
                                     "-setcookie","YMZDXGBJWIOTSAJOUHND",
                                     "-pa",
                                     "/buildroot/otp/lib/stdlib/make_test_dir/stdlib_test",
                                     "-env","ERL_CRASH_DUMP",
                                     "/buildroot/otp/lib/stdlib/make_test_dir/ct_logs/ct_run.test_server@2173de9773d8.2025-01-28_10.34.01/erl_crash_dump.peer_SUITE-cntrl_channel_handler_crash_old_release-429604-11901",
                                     "-pa",
                                     "/buildroot/otp/lib/stdlib/make_test_dir/ct_logs/ct_run.test_server@2173de9773d8.2025-01-28_10.34.01/make_test_dir.stdlib_test.logs/run.2025-01-28_10.34.36/log_private/",
                                     "-user","peer"],
                                    #Port<0.3156>,undefined,<<>>,running,
                                    {<0.258879.0>,
                                     #Ref<0.2994499957.3581935620.101603>},
                                    0,#{}}
** Reason for termination ==
** {#Ref<0.2994499957.3581935620.101088>,2141607,ok,
    [{peer_SUITE,cntrl_channel_handler_crash_old_release}],
    []}


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during standard_io in peer_SUITE 2025-01-28 10:50:47.194 ***</b>
=CRASH REPORT==== 28-Jan-2025::10:50:47.194520 ===
  crasher:
    initial call: peer:init/1
    pid: <0.258926.0>
    registered_name: []
    exception exit: {#Ref<0.2994499957.3581935620.101088>,2141607,ok,
                     [{peer_SUITE,cntrl_channel_handler_crash_old_release}],
                     []}
      in function  gen_server:decode_msg/9 (gen_server.erl, line 2301)
    ancestors: [<0.258879.0>]
    message_queue_len: 1
    messages: [{'EXIT',#Port<0.3156>,normal}]
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 2586
    stack_size: 29
    reductions: 4330
  neighbours:


</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during standard_io in peer_SUITE 2025-01-28 10:50:47.565 ***</b>
=WARNING REPORT==== 28-Jan-2025::10:50:47.565071 ===
peer:stop() timed out waiting for disconnect from node 'init_debug-388517-11901@2173de9773d8'. The connection was forcefully taken down.

</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during standard_io in peer_SUITE 2025-01-28 10:50:47.588 ***</b>
=WARNING REPORT==== 28-Jan-2025::10:50:46.584534 ===
Process <0.89.0> on node 'peer_SUITE-shutdown_stop-529922-11901@2173de9773d8' enabled access to the emulator internal state.
NOTE: This is an erts internal test feature and should *only* be used by OTP test-suites.



</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during standard_io in peer_SUITE 2025-01-28 10:50:47.990 ***</b>
=WARNING REPORT==== 28-Jan-2025::10:50:47.990107 ===
peer:stop() timed out waiting for disconnect from node 'peer_SUITE-shutdown_halt_timeout-529954-11901@2173de9773d8'. The connection was forcefully taken down.

</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during standard_io in peer_SUITE 2025-01-28 10:50:48.066 ***</b>
=WARNING REPORT==== 28-Jan-2025::10:50:48.066168 ===
peer:stop() timed out waiting for disconnect from node 'peer_SUITE-shutdown_stop_timeout-408771-11901@2173de9773d8'. The connection was forcefully taken down.

</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during supervisor_SUITE:temporary_bystander/1 2025-01-28 11:11:57.059 ***</b>
=ERROR REPORT==== 28-Jan-2025::11:11:57.059439 ===
** Generic server <0.335840.0> terminating 
** Last message in was {'EXIT',<0.335837.0>,
                               {#Ref<0.2994499957.3620470785.173747>,350696,
                                [{child1,<0.335846.0>,worker,[]}],
                                [{supervisor_SUITE,temporary_bystander}],
                                []}}
** When Server state == {state,
                            {<0.335840.0>,supervisor_SUITE},
                            rest_for_one,
                            {[child1],
                             #{child1 =>
                                   {child,<0.335846.0>,child1,
                                       {supervisor_1,start_child,[]},
                                       permanent,false,100,worker,[]}}},
                            undefined,2,300,
                            [-576458477],
                            1,0,never,supervisor_SUITE,
                            {ok,{{rest_for_one,2,300},[]}}}
** Reason for termination ==
** {#Ref<0.2994499957.3620470785.173747>,350696,
    [{child1,<0.335846.0>,worker,[]}],
    [{supervisor_SUITE,temporary_bystander}],
    []}


</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during supervisor_SUITE:temporary_bystander/1 2025-01-28 11:11:57.059 ***</b>
=ERROR REPORT==== 28-Jan-2025::11:11:57.059444 ===
** Generic server <0.335839.0> terminating 
** Last message in was {'EXIT',<0.335837.0>,
                               {#Ref<0.2994499957.3620470785.173747>,350696,
                                [{child1,<0.335846.0>,worker,[]}],
                                [{supervisor_SUITE,temporary_bystander}],
                                []}}
** When Server state == {state,
                            {<0.335839.0>,supervisor_SUITE},
                            one_for_all,
                            {[child1],
                             #{child1 =>
                                   {child,<0.335845.0>,child1,
                                       {supervisor_1,start_child,[]},
                                       permanent,false,100,worker,[]}}},
                            undefined,2,300,
                            [-576458477],
                            1,0,never,supervisor_SUITE,
                            {ok,{{one_for_all,2,300},[]}}}
** Reason for termination ==
** {#Ref<0.2994499957.3620470785.173747>,350696,
    [{child1,<0.335846.0>,worker,[]}],
    [{supervisor_SUITE,temporary_bystander}],
    []}


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during supervisor_SUITE:temporary_bystander/1 2025-01-28 11:11:57.060 ***</b>
=CRASH REPORT==== 28-Jan-2025::11:11:57.059761 ===
  crasher:
    initial call: supervisor:supervisor_SUITE/1
    pid: <0.335840.0>
    registered_name: []
    exception exit: {#Ref<0.2994499957.3620470785.173747>,350696,
                     [{child1,<0.335846.0>,worker,[]}],
                     [{supervisor_SUITE,temporary_bystander}],
                     []}
      in function  gen_server:decode_msg/9 (gen_server.erl, line 2301)
    ancestors: [<0.335837.0>]
    message_queue_len: 0
    messages: []
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 1598
    stack_size: 29
    reductions: 1027
  neighbours:


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during supervisor_SUITE:temporary_bystander/1 2025-01-28 11:11:57.060 ***</b>
=CRASH REPORT==== 28-Jan-2025::11:11:57.059912 ===
  crasher:
    initial call: supervisor:supervisor_SUITE/1
    pid: <0.335839.0>
    registered_name: []
    exception exit: {#Ref<0.2994499957.3620470785.173747>,350696,
                     [{child1,<0.335846.0>,worker,[]}],
                     [{supervisor_SUITE,temporary_bystander}],
                     []}
      in function  gen_server:decode_msg/9 (gen_server.erl, line 2301)
    ancestors: [<0.335837.0>]
    message_queue_len: 0
    messages: []
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 1598
    stack_size: 29
    reductions: 1010
  neighbours:


</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during zzz_SUITE:lc_graph/1 2025-01-28 11:38:24.996 ***</b>
=WARNING REPORT==== 28-Jan-2025::11:38:24.992953 ===
Process <0.439500.0> on node 'test_server@2173de9773d8' enabled access to the emulator internal state.
NOTE: This is an erts internal test feature and should *only* be used by OTP test-suites.



</pre></div>
<pre>
</pre>
<center>
<br /><hr /><p>
<a href="../../../all_runs.html">Test run history
</a>  |  <a href="../../../index.html">Top level test index
</a>  |  <a href="../../../suite.log.latest.html">Latest test result</a>
</p>
<div class="copyright">Copyright &copy; 2025 <a href="http://www.erlang.org">Open Telecom Platform</a><br />
Updated: <!--date-->Tue Jan 28 2025 10:34:36<!--/date--><br />
</div>
</center>
</body>
</html>
