
=====
===== LOGGING STARTED Mon Mar  4 21:04:25 CET 2024
=====

=====
===== LOGGING STARTED Mon Mar  4 21:04:25 CET 2024
=====
Erlang/OTP 27 [RELEASE CANDIDATE 1] [erts-14.2.2] [source] [64-bit] [smp:1:1] [ds:1:1:1] [async-threads:1] [jit:ns]

Erlang/OTP 27 [RELEASE CANDIDATE 1] [erts-14.2.2] [source] [64-bit] [smp:1:1] [ds:1:1:1] [async-threads:1] [jit:ns]

Logger - error: {removed_failing_handler,default}
Failed to write log message to stdout, trying stderr
=CRASH REPORT==== 4-Mar-2024::21:04:26.939995 ===
  crasher:
    initial call: peer:init_supervision/2
    pid: <0.70.0>
    registered_name: peer_supervision
    exception exit: {peer_channel_terminated,killed}
      in function  peer:loop_supervision/1 (peer.erl, line 1303)
      in call from peer:init_supervision/2 (peer.erl, line 1281)
    ancestors: [kernel_sup,<0.46.0>]
    message_queue_len: 0
    messages: []
    links: [<0.48.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 376
    stack_size: 29
    reductions: 81
  neighbours:

Kernel pid terminated (application_controller) ("{application_terminated,kernel,shutdown}")

Crash dump is being written to: /buildroot/otp/lib/stdlib/make_test_dir/stdlib_erl_crash.dump...done

=====
===== LOGGING STARTED Mon Mar  4 21:04:41 CET 2024
=====

=====
===== LOGGING STARTED Mon Mar  4 21:04:42 CET 2024
=====
Erlang/OTP 27 [RELEASE CANDIDATE 1] [erts-14.2.2] [source] [64-bit] [smp:1:1] [ds:1:1:1] [async-threads:1] [jit:ns]

Erlang/OTP 27 [RELEASE CANDIDATE 1] [erts-14.2.2] [source] [64-bit] [smp:1:1] [ds:1:1:1] [async-threads:1] [jit:ns]

=CRASH REPORT==== 4-Mar-2024::21:04:43.701279 ===
  crasher:
    initial call: peer:init_supervision/2
    pid: <0.70.0>
    registered_name: peer_supervision
    exception exit: {peer_channel_terminated,killed}
      in function  peer:loop_supervision/1 (peer.erl, line 1303)
      in call from peer:init_supervision/2 (peer.erl, line 1281)
    ancestors: [kernel_sup,<0.46.0>]
    message_queue_len: 0
    messages: []
    links: [<0.48.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 376
    stack_size: 29
    reductions: 81
  neighbours:

=SUPERVISOR REPORT==== 4-Mar-2024::21:04:43.728678 ===
    supervisor: {local,kernel_sup}
    errorContext: child_terminated
    reason: {peer_channel_terminated,killed}
    offender: [{pid,<0.70.0>},
               {id,peer_supervision},
               {mfargs,{peer,start_supervision,[]}},
               {restart_type,permanent},
               {significant,false},
               {shutdown,1000},
               {child_type,worker}]

=SUPERVISOR REPORT==== 4-Mar-2024::21:04:43.728824 ===
    supervisor: {local,kernel_sup}
    errorContext: shutdown
    reason: reached_max_restart_intensity
    offender: [{pid,<0.70.0>},
               {id,peer_supervision},
               {mfargs,{peer,start_supervision,[]}},
               {restart_type,permanent},
               {significant,false},
               {shutdown,1000},
               {child_type,worker}]

Eshell V14.2.2 (press Ctrl+G to abort, type help(). for help)
(peer_SUITE-attached_test-558466-11804@42666827045c)1> Kernel pid terminated (application_controller) ("{application_terminated,kernel,shutdown}")

Crash dump is being written to: /buildroot/otp/lib/stdlib/make_test_dir/stdlib_erl_crash.dump...done
