<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<title>Unexpected I/O log</title>
<meta http-equiv="cache-control" content="no-cache"></meta>
<meta http-equiv="content-type" content="text/html; charset=utf-8"></meta>
<link rel="stylesheet" href="../../ct_default.css" type="text/css"></link>
<script type="text/javascript" src="../../jquery-latest.js"></script>
<script type="text/javascript" src="../../jquery.tablesorter.min.js"></script>
</head>
<body>

<br />
<h3>Unexpected I/O</h3>
<pre>

</pre>
<div class="error_logger"><pre><b>*** System report during multi_call_parallel in gen_server_SUITE 2025-01-10 16:01:21.995 ***</b>
=ERROR REPORT==== 10-Jan-2025::16:01:21.995451 ===
** Generic server my_test_name terminating 
** Last message in was stop
** When Server state == {formatted,[]}
** Reason for termination ==
** stopped
** Client <0.245671.0> stacktrace
** [{gen_server,mc_recv,5,[{file,"gen_server.erl"},{line,1973}]},
    {gen_server,multi_call,4,[{file,"gen_server.erl"},{line,1934}]},
    {gen_server_SUITE,multicall,1,[{file,"gen_server_SUITE.erl"},{line,1487}]},
    {test_server,ts_tc,3,[{file,"test_server.erl"},{line,1794}]},
    {test_server,run_test_case_eval1,6,[{file,"test_server.erl"},{line,1303}]},
    {test_server,run_test_case_eval,9,[{file,"test_server.erl"},{line,1235}]}]


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during multi_call_parallel in gen_server_SUITE 2025-01-10 16:01:21.996 ***</b>
=CRASH REPORT==== 10-Jan-2025::16:01:21.995807 ===
  crasher:
    initial call: gen_server_SUITE:init/1
    pid: <0.245677.0>
    registered_name: my_test_name
    exception exit: stopped
      in function  gen_server:handle_msg/6 (gen_server.erl, line 2426)
    ancestors: [<0.245671.0>]
    message_queue_len: 0
    messages: []
    links: [<0.245671.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 987
    stack_size: 29
    reductions: 594
  neighbours:


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during gen_server_SUITE:spec_init/1 2025-01-10 16:02:01.881 ***</b>
=ERROR REPORT==== 10-Jan-2025::16:02:01.881028 ===
** Generic server hurra terminating 
** Last message in was {'EXIT',&lt;0.250022.0&gt;,
                               {#Ref&lt;0.2450114186.4183031809.217635&gt;,1004375,
                                ok,
                                [{gen_server_SUITE,spec_init}],
                                []}}
** When Server state == {formatted,{}}
** Reason for termination ==
** {#Ref&lt;0.2450114186.4183031809.217635&gt;,1004375,ok,
    [{gen_server_SUITE,spec_init}],
    []}


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during gen_server_SUITE:spec_init/1 2025-01-10 16:02:01.881 ***</b>
=CRASH REPORT==== 10-Jan-2025::16:02:01.881300 ===
  crasher:
    initial call: gen_server_SUITE:spec_init_global_default_timeout/2
    pid: &lt;0.250042.0&gt;
    registered_name: []
    exception exit: {#Ref&lt;0.2450114186.4183031809.217635&gt;,1004375,ok,
                     [{gen_server_SUITE,spec_init}],
                     []}
      in function  gen_server:decode_msg/9 (gen_server.erl, line 2299)
    ancestors: [&lt;0.250022.0&gt;]
    message_queue_len: 0
    messages: []
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 29
    reductions: 414
  neighbours:


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during gen_server_SUITE:spec_init_local_registered_parent/1 2025-01-10 16:02:01.904 ***</b>
=CRASH REPORT==== 10-Jan-2025::16:02:01.904038 ===
  crasher:
    initial call: gen_server_SUITE:spec_init_local/2
    pid: &lt;0.250048.0&gt;
    registered_name: my_server
    exception exit: {&lt;0.250046.0&gt;,stopped}
      in function  gen_server:handle_common_reply/8 (gen_server.erl, line 2476)
    ancestors: [foobar]
    message_queue_len: 0
    messages: []
    links: [&lt;0.250046.0&gt;]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 29
    reductions: 400
  neighbours:


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during log_mf_h_SUITE:test/1 2025-01-10 16:06:43.438 ***</b>
=CRASH REPORT==== 10-Jan-2025::16:06:43.437856 ===
  crasher:
    initial call: gen_event:init_it/6
    pid: &lt;0.255853.0&gt;
    registered_name: []
    exception exit: {#Ref&lt;0.2450114186.4184604673.103298&gt;,5699,
                     {ok,3},
                     [{log_mf_h_SUITE,test}],
                     []}
      in function  gen_event:terminate_server/4 (gen_event.erl, line 1694)
    ancestors: [&lt;0.255851.0&gt;]
    message_queue_len: 0
    messages: []
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 6772
    stack_size: 29
    reductions: 28126
  neighbours:


</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during dist in peer_SUITE 2025-01-10 16:06:52.738 ***</b>
=ERROR REPORT==== 10-Jan-2025::16:06:52.738134 ===
** Generic server <0.257155.0> terminating 
** Last message in was {nodedown,'peer_down_crash-490210-11968@a4374a72bd19'}
** When Server state == {peer_state,
                            #{args => ["-connect_all","false"],
                              name => "peer_down_crash-490210-11968",
                              peer_down => crash},
                            'peer_down_crash-490210-11968@a4374a72bd19',
                            [47,98,117,105,108,100,114,111,111,116,47,111,116,
                             112,47,69,114,108,97,110,103,32,8709,8868,8478,
                             47,101,114,116,115,45,49,53,46,50,47,98,105,110,
                             47,101,114,108],
                            ["-sname","peer_down_crash-490210-11968",
                             "-connect_all","false","-detached",
                             "-peer_detached","-user","peer","-origin",
                             "g1h3GHRlc3Rfc2VydmVyQGE0Mzc0YTcyYmQxOQAD7IMAAAAAZ4Ez6w=="],
                            undefined,undefined,<<>>,
                            {down,
                                {nodedown,
                                    'peer_down_crash-490210-11968@a4374a72bd19'}},
                            {<0.257125.0>,
                             #Ref<0.2450114186.4184604673.119382>},
                            0,#{}}
** Reason for termination ==
** {nodedown,'peer_down_crash-490210-11968@a4374a72bd19'}


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during dist in peer_SUITE 2025-01-10 16:06:52.738 ***</b>
=CRASH REPORT==== 10-Jan-2025::16:06:52.738452 ===
  crasher:
    initial call: peer:init/1
    pid: <0.257155.0>
    registered_name: []
    exception exit: {nodedown,'peer_down_crash-490210-11968@a4374a72bd19'}
      in function  gen_server:handle_common_reply/8 (gen_server.erl, line 2476)
    ancestors: [<0.257125.0>]
    message_queue_len: 0
    messages: []
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 1598
    stack_size: 29
    reductions: 1482
  neighbours:


</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during dist in peer_SUITE 2025-01-10 16:06:53.754 ***</b>
=WARNING REPORT==== 10-Jan-2025::16:06:52.752437 ===
Process <0.92.0> on node 'peer_SUITE-shutdown_stop-490306-11968@a4374a72bd19' enabled access to the emulator internal state.
NOTE: This is an erts internal test feature and should *only* be used by OTP test-suites.



</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during dist in peer_SUITE 2025-01-10 16:06:54.177 ***</b>
=WARNING REPORT==== 10-Jan-2025::16:06:54.177427 ===
peer:stop() timed out waiting for disconnect from node 'peer_SUITE-shutdown_stop_timeout-446691-11968@a4374a72bd19'. The connection was forcefully taken down.

</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during dist in peer_SUITE 2025-01-10 16:06:54.275 ***</b>
=WARNING REPORT==== 10-Jan-2025::16:06:54.275332 ===
peer:stop() timed out waiting for disconnect from node 'peer_SUITE-shutdown_halt_timeout-490274-11968@a4374a72bd19'. The connection was forcefully taken down.

</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during tcp in peer_SUITE 2025-01-10 16:07:09.824 ***</b>
=WARNING REPORT==== 10-Jan-2025::16:07:08.822988 ===
Process <0.89.0> on node 'peer_SUITE-shutdown_halt-446851-11968@a4374a72bd19' enabled access to the emulator internal state.
NOTE: This is an erts internal test feature and should *only* be used by OTP test-suites.



</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during tcp in peer_SUITE 2025-01-10 16:07:09.856 ***</b>
=WARNING REPORT==== 10-Jan-2025::16:07:08.854623 ===
Process <0.89.0> on node 'peer_SUITE-shutdown_stop-459717-11968@a4374a72bd19' enabled access to the emulator internal state.
NOTE: This is an erts internal test feature and should *only* be used by OTP test-suites.



</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during tcp in peer_SUITE 2025-01-10 16:07:10.237 ***</b>
=WARNING REPORT==== 10-Jan-2025::16:07:10.237423 ===
peer:stop() timed out waiting for disconnect from node 'peer_SUITE-shutdown_stop_timeout-446883-11968@a4374a72bd19'. The connection was forcefully taken down.

</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during tcp in peer_SUITE 2025-01-10 16:07:10.302 ***</b>
=WARNING REPORT==== 10-Jan-2025::16:07:10.302400 ===
peer:stop() timed out waiting for disconnect from node 'peer_SUITE-shutdown_halt_timeout-459685-11968@a4374a72bd19'. The connection was forcefully taken down.

</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during standard_io in peer_SUITE 2025-01-10 16:07:12.495 ***</b>
=ERROR REPORT==== 10-Jan-2025::16:07:12.494802 ===
** Generic server <0.257498.0> terminating 
** Last message in was {'EXIT',<0.257478.0>,
                               {#Ref<0.2450114186.4177526786.28787>,1541565,
                                ok,
                                [{peer_SUITE,cntrl_channel_handler_crash}],
                                []}}
** When Server state == {peer_state,#{name =>
                                          "peer_SUITE-cntrl_channel_handler_crash-491106-11968",
                                      connection => standard_io},
                                    'peer_SUITE-cntrl_channel_handler_crash-491106-11968@a4374a72bd19',
                                    [47,98,117,105,108,100,114,111,111,116,47,
                                     111,116,112,47,69,114,108,97,110,103,32,
                                     8709,8868,8478,47,101,114,116,115,45,49,
                                     53,46,50,47,98,105,110,47,101,114,108],
                                    ["-sname",
                                     "peer_SUITE-cntrl_channel_handler_crash-491106-11968",
                                     "-user","peer"],
                                    #Port<0.3132>,undefined,<<>>,running,
                                    {<0.257478.0>,
                                     #Ref<0.2450114186.4184604673.122369>},
                                    0,#{}}
** Reason for termination ==
** {#Ref<0.2450114186.4177526786.28787>,1541565,ok,
    [{peer_SUITE,cntrl_channel_handler_crash}],
    []}


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during standard_io in peer_SUITE 2025-01-10 16:07:12.495 ***</b>
=CRASH REPORT==== 10-Jan-2025::16:07:12.495164 ===
  crasher:
    initial call: peer:init/1
    pid: <0.257498.0>
    registered_name: []
    exception exit: {#Ref<0.2450114186.4177526786.28787>,1541565,ok,
                     [{peer_SUITE,cntrl_channel_handler_crash}],
                     []}
      in function  gen_server:decode_msg/9 (gen_server.erl, line 2299)
    ancestors: [<0.257478.0>]
    message_queue_len: 1
    messages: [{'EXIT',#Port<0.3132>,normal}]
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 2586
    stack_size: 29
    reductions: 4132
  neighbours:


</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during standard_io in peer_SUITE 2025-01-10 16:07:13.086 ***</b>
=ERROR REPORT==== 10-Jan-2025::16:07:13.086459 ===
** Generic server <0.257524.0> terminating 
** Last message in was {'EXIT',<0.257497.0>,
                           {#Ref<0.2450114186.4184604673.122312>,2136620,ok,
                            [{peer_SUITE,
                                 cntrl_channel_handler_crash_old_release}],
                            []}}
** When Server state == {peer_state,#{args =>
                                          ["-setcookie",
                                           "VRNZKNRCOJAGQQAVAKJK","-pa",
                                           "/buildroot/otp/lib/stdlib/make_test_dir/stdlib_test",
                                           "-env","ERL_CRASH_DUMP",
                                           "/buildroot/otp/lib/stdlib/make_test_dir/ct_logs/ct_run.test_server@a4374a72bd19.2025-01-10_15.51.22/erl_crash_dump.peer_SUITE-cntrl_channel_handler_crash_old_release-491138-11968",
                                           "-pa",
                                           "/buildroot/otp/lib/stdlib/make_test_dir/ct_logs/ct_run.test_server@a4374a72bd19.2025-01-10_15.51.22/make_test_dir.stdlib_test.logs/run.2025-01-10_15.51.57/log_private/"],
                                      env => [{"ERL_AFLAGS",false}],
                                      name =>
                                          "peer_SUITE-cntrl_channel_handler_crash_old_release-491138-11968",
                                      connection => standard_io,
                                      exec =>
                                          "/usr/local/lib/erlang-26.2.5.6/bin/erl",
                                      start_cover => false},
                                    'peer_SUITE-cntrl_channel_handler_crash_old_release-491138-11968@a4374a72bd19',
                                    "/usr/local/lib/erlang-26.2.5.6/bin/erl",
                                    ["-sname",
                                     "peer_SUITE-cntrl_channel_handler_crash_old_release-491138-11968",
                                     "-setcookie","VRNZKNRCOJAGQQAVAKJK",
                                     "-pa",
                                     "/buildroot/otp/lib/stdlib/make_test_dir/stdlib_test",
                                     "-env","ERL_CRASH_DUMP",
                                     "/buildroot/otp/lib/stdlib/make_test_dir/ct_logs/ct_run.test_server@a4374a72bd19.2025-01-10_15.51.22/erl_crash_dump.peer_SUITE-cntrl_channel_handler_crash_old_release-491138-11968",
                                     "-pa",
                                     "/buildroot/otp/lib/stdlib/make_test_dir/ct_logs/ct_run.test_server@a4374a72bd19.2025-01-10_15.51.22/make_test_dir.stdlib_test.logs/run.2025-01-10_15.51.57/log_private/",
                                     "-user","peer"],
                                    #Port<0.3157>,undefined,<<>>,running,
                                    {<0.257497.0>,
                                     #Ref<0.2450114186.4177526786.29372>},
                                    0,#{}}
** Reason for termination ==
** {#Ref<0.2450114186.4184604673.122312>,2136620,ok,
    [{peer_SUITE,cntrl_channel_handler_crash_old_release}],
    []}


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during standard_io in peer_SUITE 2025-01-10 16:07:13.087 ***</b>
=CRASH REPORT==== 10-Jan-2025::16:07:13.086908 ===
  crasher:
    initial call: peer:init/1
    pid: <0.257524.0>
    registered_name: []
    exception exit: {#Ref<0.2450114186.4184604673.122312>,2136620,ok,
                     [{peer_SUITE,cntrl_channel_handler_crash_old_release}],
                     []}
      in function  gen_server:decode_msg/9 (gen_server.erl, line 2299)
    ancestors: [<0.257497.0>]
    message_queue_len: 1
    messages: [{'EXIT',#Port<0.3157>,normal}]
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 2586
    stack_size: 29
    reductions: 4327
  neighbours:


</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during standard_io in peer_SUITE 2025-01-10 16:07:13.456 ***</b>
=WARNING REPORT==== 10-Jan-2025::16:07:13.456473 ===
peer:stop() timed out waiting for disconnect from node 'init_debug-359044-11968@a4374a72bd19'. The connection was forcefully taken down.

</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during standard_io in peer_SUITE 2025-01-10 16:07:13.505 ***</b>
=WARNING REPORT==== 10-Jan-2025::16:07:12.503803 ===
Process <0.89.0> on node 'peer_SUITE-shutdown_stop-459813-11968@a4374a72bd19' enabled access to the emulator internal state.
NOTE: This is an erts internal test feature and should *only* be used by OTP test-suites.



</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during standard_io in peer_SUITE 2025-01-10 16:07:13.767 ***</b>
=WARNING REPORT==== 10-Jan-2025::16:07:13.767393 ===
peer:stop() timed out waiting for disconnect from node 'peer_SUITE-shutdown_stop_timeout-459781-11968@a4374a72bd19'. The connection was forcefully taken down.

</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during standard_io in peer_SUITE 2025-01-10 16:07:13.984 ***</b>
=WARNING REPORT==== 10-Jan-2025::16:07:13.984374 ===
peer:stop() timed out waiting for disconnect from node 'peer_SUITE-shutdown_halt_timeout-459845-11968@a4374a72bd19'. The connection was forcefully taken down.

</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during supervisor_SUITE:temporary_bystander/1 2025-01-10 16:28:20.518 ***</b>
=ERROR REPORT==== 10-Jan-2025::16:28:20.517789 ===
** Generic server <0.334413.0> terminating 
** Last message in was {'EXIT',<0.334411.0>,
                               {#Ref<0.2450114186.4193255426.16928>,351031,
                                [{child1,<0.334420.0>,worker,[]}],
                                [{supervisor_SUITE,temporary_bystander}],
                                []}}
** When Server state == {state,
                            {<0.334413.0>,supervisor_SUITE},
                            one_for_all,
                            {[child1],
                             #{child1 =>
                                   {child,<0.334419.0>,child1,
                                       {supervisor_1,start_child,[]},
                                       permanent,false,100,worker,[]}}},
                            undefined,2,300,
                            [-576458534],
                            1,0,never,supervisor_SUITE,
                            {ok,{{one_for_all,2,300},[]}}}
** Reason for termination ==
** {#Ref<0.2450114186.4193255426.16928>,351031,
    [{child1,<0.334420.0>,worker,[]}],
    [{supervisor_SUITE,temporary_bystander}],
    []}


</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during supervisor_SUITE:temporary_bystander/1 2025-01-10 16:28:20.518 ***</b>
=ERROR REPORT==== 10-Jan-2025::16:28:20.517795 ===
** Generic server <0.334414.0> terminating 
** Last message in was {'EXIT',<0.334411.0>,
                               {#Ref<0.2450114186.4193255426.16928>,351031,
                                [{child1,<0.334420.0>,worker,[]}],
                                [{supervisor_SUITE,temporary_bystander}],
                                []}}
** When Server state == {state,
                            {<0.334414.0>,supervisor_SUITE},
                            rest_for_one,
                            {[child1],
                             #{child1 =>
                                   {child,<0.334420.0>,child1,
                                       {supervisor_1,start_child,[]},
                                       permanent,false,100,worker,[]}}},
                            undefined,2,300,
                            [-576458534],
                            1,0,never,supervisor_SUITE,
                            {ok,{{rest_for_one,2,300},[]}}}
** Reason for termination ==
** {#Ref<0.2450114186.4193255426.16928>,351031,
    [{child1,<0.334420.0>,worker,[]}],
    [{supervisor_SUITE,temporary_bystander}],
    []}


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during supervisor_SUITE:temporary_bystander/1 2025-01-10 16:28:20.518 ***</b>
=CRASH REPORT==== 10-Jan-2025::16:28:20.518227 ===
  crasher:
    initial call: supervisor:supervisor_SUITE/1
    pid: <0.334413.0>
    registered_name: []
    exception exit: {#Ref<0.2450114186.4193255426.16928>,351031,
                     [{child1,<0.334420.0>,worker,[]}],
                     [{supervisor_SUITE,temporary_bystander}],
                     []}
      in function  gen_server:decode_msg/9 (gen_server.erl, line 2299)
    ancestors: [<0.334411.0>]
    message_queue_len: 0
    messages: []
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 1598
    stack_size: 29
    reductions: 1010
  neighbours:


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during supervisor_SUITE:temporary_bystander/1 2025-01-10 16:28:20.518 ***</b>
=CRASH REPORT==== 10-Jan-2025::16:28:20.518428 ===
  crasher:
    initial call: supervisor:supervisor_SUITE/1
    pid: <0.334414.0>
    registered_name: []
    exception exit: {#Ref<0.2450114186.4193255426.16928>,351031,
                     [{child1,<0.334420.0>,worker,[]}],
                     [{supervisor_SUITE,temporary_bystander}],
                     []}
      in function  gen_server:decode_msg/9 (gen_server.erl, line 2299)
    ancestors: [<0.334411.0>]
    message_queue_len: 0
    messages: []
    links: []
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 1598
    stack_size: 29
    reductions: 1027
  neighbours:


</pre></div>
<pre>
</pre>
<div class="sasl"><pre><b>*** System report during supervisor_bridge_SUITE:simple_global_supervisor/1 2025-01-10 16:29:03.985 ***</b>
=CRASH REPORT==== 10-Jan-2025::16:29:03.985556 ===
  crasher:
    initial call: supervisor_bridge:supervisor_bridge_SUITE/1
    pid: <0.434583.0>
    registered_name: []
    exception exit: killed
      in function  gen_server:decode_msg/9 (gen_server.erl, line 2299)
    ancestors: [bridge9212,<0.434578.0>]
    message_queue_len: 0
    messages: []
    links: [<0.434584.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 610
    stack_size: 29
    reductions: 388
  neighbours:
    neighbour:
      pid: <0.434584.0>
      registered_name: work_supervisor_bridge_SUITE_server
      initial_call: {supervisor_bridge_SUITE,internal_loop_init,1}
      current_function: {supervisor_bridge_SUITE,internal_loop,1}
      ancestors: []
      message_queue_len: 0
      links: [<0.434583.0>]
      trap_exit: false
      status: waiting
      heap_size: 233
      stack_size: 3
      reductions: 9
      current_stacktrace: [{supervisor_bridge_SUITE,internal_loop,1,
                      [{file,"supervisor_bridge_SUITE.erl"},{line,152}]}]

</pre></div>
<pre>
</pre>
<div class="error_logger"><pre><b>*** System report during zzz_SUITE:lc_graph/1 2025-01-10 16:54:22.954 ***</b>
=WARNING REPORT==== 10-Jan-2025::16:54:22.950992 ===
Process <0.438089.0> on node 'test_server@a4374a72bd19' enabled access to the emulator internal state.
NOTE: This is an erts internal test feature and should *only* be used by OTP test-suites.



</pre></div>
<pre>
</pre>
<center>
<br /><hr /><p>
<a href="../../../all_runs.html">Test run history
</a>  |  <a href="../../../index.html">Top level test index
</a>  |  <a href="../../../suite.log.latest.html">Latest test result</a>
</p>
<div class="copyright">Copyright &copy; 2025 <a href="http://www.erlang.org">Open Telecom Platform</a><br />
Updated: <!--date-->Fri Jan 10 2025 15:51:57<!--/date--><br />
</div>
</center>
</body>
</html>
