
=====
===== LOGGING STARTED Wed Apr 17 17:47:47 CEST 2024
=====

=====
===== LOGGING STARTED Wed Apr 17 17:47:47 CEST 2024
=====
Erlang/OTP 27 [RELEASE CANDIDATE 2] [erts-14.2.4] [source] [64-bit] [smp:1:1] [ds:1:1:1] [async-threads:1] [jit:ns]

Erlang/OTP 27 [RELEASE CANDIDATE 2] [erts-14.2.4] [source] [64-bit] [smp:1:1] [ds:1:1:1] [async-threads:1] [jit:ns]

=CRASH REPORT==== 17-Apr-2024::17:47:48.455043 ===
  crasher:
    initial call: peer:init_supervision/2
    pid: <0.71.0>
    registered_name: peer_supervision
    exception exit: {peer_channel_terminated,killed}
      in function  peer:loop_supervision/1 (peer.erl, line 1303)
      in call from peer:init_supervision/2 (peer.erl, line 1281)
    ancestors: [kernel_sup,<0.47.0>]
    message_queue_len: 0
    messages: []
    links: [<0.49.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 376
    stack_size: 29
    reductions: 81
  neighbours:

=SUPERVISOR REPORT==== 17-Apr-2024::17:47:48.504629 ===
    supervisor: {local,kernel_sup}
    errorContext: child_terminated
    reason: {peer_channel_terminated,killed}
    offender: [{pid,<0.71.0>},
               {id,peer_supervision},
               {mfargs,{peer,start_supervision,[]}},
               {restart_type,permanent},
               {significant,false},
               {shutdown,1000},
               {child_type,worker}]

=SUPERVISOR REPORT==== 17-Apr-2024::17:47:48.504753 ===
    supervisor: {local,kernel_sup}
    errorContext: shutdown
    reason: reached_max_restart_intensity
    offender: [{pid,<0.71.0>},
               {id,peer_supervision},
               {mfargs,{peer,start_supervision,[]}},
               {restart_type,permanent},
               {significant,false},
               {shutdown,1000},
               {child_type,worker}]

Eshell V14.2.4 (press Ctrl+G to abort, type help(). for help)
(peer_SUITE-attached_test-418405-11893@af73530ee214)1> *** ERROR: Shell process terminated! ***
Kernel pid terminated (application_controller) ("{application_terminated,kernel,shutdown}")

Crash dump is being written to: /buildroot/otp/lib/stdlib/make_test_dir/stdlib_erl_crash.dump...done

=====
===== LOGGING STARTED Wed Apr 17 17:48:05 CEST 2024
=====

=====
===== LOGGING STARTED Wed Apr 17 17:48:05 CEST 2024
=====
Erlang/OTP 27 [RELEASE CANDIDATE 2] [erts-14.2.4] [source] [64-bit] [smp:1:1] [ds:1:1:1] [async-threads:1] [jit:ns]

Erlang/OTP 27 [RELEASE CANDIDATE 2] [erts-14.2.4] [source] [64-bit] [smp:1:1] [ds:1:1:1] [async-threads:1] [jit:ns]

Eshell V14.2.4 (press Ctrl+G to abort, type help(). for help)
(peer_SUITE-attached_test-467587-11893@af73530ee214)1> *** ERROR: Shell process terminated! ***
=ERROR REPORT==== 17-Apr-2024::17:48:06.870610 ===
Error in process <0.79.0> on node 'peer_SUITE-attached_test-467587-11893@af73530ee214' with exit value:
{{case_clause,<0.122.0>},
 [{group,edit_line,2,[{file,"group.erl"},{line,1000}]},
  {group,get_line_echo_off,5,[{file,"group.erl"},{line,885}]},
  {group,get_chars_loop,10,[{file,"group.erl"},{line,518}]},
  {group,io_request,6,[{file,"group.erl"},{line,211}]},
  {group,server_loop,3,[{file,"group.erl"},{line,137}]}]}

Eshell V14.2.4 (press Ctrl+G to abort, type help(). for help)
(peer_SUITE-attached_test-467587-11893@af73530ee214)1> =CRASH REPORT==== 17-Apr-2024::17:48:06.871133 ===
  crasher:
    initial call: peer:init_supervision/2
    pid: <0.71.0>
    registered_name: peer_supervision
    exception exit: {peer_channel_terminated,killed}
      in function  peer:loop_supervision/1 (peer.erl, line 1303)
      in call from peer:init_supervision/2 (peer.erl, line 1281)
    ancestors: [kernel_sup,<0.47.0>]
    message_queue_len: 0
    messages: []
    links: [<0.49.0>]
    dictionary: []
    trap_exit: true
    status: running
    heap_size: 376
    stack_size: 29
    reductions: 81
  neighbours:

=SUPERVISOR REPORT==== 17-Apr-2024::17:48:06.881399 ===
    supervisor: {local,kernel_sup}
    errorContext: child_terminated
    reason: {peer_channel_terminated,killed}
    offender: [{pid,<0.71.0>},
               {id,peer_supervision},
               {mfargs,{peer,start_supervision,[]}},
               {restart_type,permanent},
               {significant,false},
               {shutdown,1000},
               {child_type,worker}]

=SUPERVISOR REPORT==== 17-Apr-2024::17:48:06.881541 ===
    supervisor: {local,kernel_sup}
    errorContext: shutdown
    reason: reached_max_restart_intensity
    offender: [{pid,<0.71.0>},
               {id,peer_supervision},
               {mfargs,{peer,start_supervision,[]}},
               {restart_type,permanent},
               {significant,false},
               {shutdown,1000},
               {child_type,worker}]

Kernel pid terminated (application_controller) ("{application_terminated,kernel,shutdown}")

Crash dump is being written to: /buildroot/otp/lib/stdlib/make_test_dir/stdlib_erl_crash.dump...done
